name: Hourly

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

env:
  CI_COMMIT_SHA: ${{ github.sha }}
  CI_COMMIT_REF_PROTECTED: ${{ github.ref_protected }}
  CI_JOB_NAME: ${{ github.job }}
  CI_JOB_ID: ${{ github.job }} # github does not expose this variable https://github.com/orgs/community/discussions/8945
  CI_JOB_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  CI_PIPELINE_SOURCE: ${{ github.event_name }}
  CI_PROJECT_DIR: ${{ github.workspace }}
  CI_MERGE_REQUEST_TARGET_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}
  ROOT_PIPELINE_ID: ${{ github.run_id }}
  BAZEL_STARTUP_ARGS: "--output_base=/var/tmp/bazel-output/"
  RUSTFLAGS: "--remap-path-prefix=${CI_PROJECT_DIR}=/ic"
  AWS_SHARED_CREDENTIALS_CONTENT: ${{ secrets.AWS_SHARED_CREDENTIALS_FILE }}

anchors:
  image: &image
      image: dfinity/ic-build:abbdc66c19bf32eda2109f97e39fde519ef9b452ab54aee52b234af8638983d8
  bazel-large-setup: &bazel-large-setup
    runs-on:
      labels: bazel-runner-large
    container:
      <<: *image
    timeout-minutes: 120
    if: ${{ vars.RUN_CI == 'true' }} # needed to avoid running on public dfinity org until published
  checkout: &checkout
    name: Checkout
    uses: actions/checkout@v4

jobs:
  bazel-system-test-hourly:
    name: Bazel-System-Test-Hourly
    <<: *bazel-large-setup
    steps:
      - <<: *checkout
        uses: actions/checkout@v3
      - name: Run Bazel System Test Hourly
        id: bazel-test-all
        uses:  ./.github/actions/bazel-test-all/
        with:
          BAZEL_COMMAND: "test"
          BAZEL_TARGETS: "//... --deleted_packages=gitlab-ci/src/gitlab_config"
          BAZEL_CI_CONFIG: "--config=ci --repository_cache=/cache/bazel"
          BAZEL_EXTRA_ARGS: "--keep_going --verbose_failures --test_tag_filters=system_test_hourly"
      - name: After script
        run: |
          bazel clean
