[package]
name = "ic-registry-subnet-type"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
ic-protobuf = { path = "../../protobuf" }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
