[package]
name = "wasm-api"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[build-dependencies]
bindgen = "0.65.1"

[dependencies]
wasm-api-sys = { path = "../wasm-api-sys" }
