[package]
name = "create_acme_account"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.18", features = ["derive"] }
instant-acme = "0.1.0"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
