[package]
name = "ic-node-rewards-canister-api"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
candid = { workspace = true }
serde = { workspace = true }
ic-base-types = { path = "../../../types/base_types" }
rewards-calculation = { path = "../../rewards_calculation" }
chrono = { workspace = true }
rust_decimal = "1.37.1"
