[package]
name = "ic-node-rewards-canister-api"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
candid = { workspace = true }
chrono = { version = "0.4.41", default-features = false, features = [] }
ic-base-types = { path = "../../../types/base_types" }
rewards-calculation = { path = "../../rewards_calculation" }
rust_decimal = "1.36.0"
serde = { workspace = true }
