[package]
name = "boundary-node-control-plane"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
arc-swap = "1.6.0"
async-scoped = { version = "0.7", features = ["use-tokio"] }
async-trait = "0.1.56"
axum = "0.6.1"
bytes = { workspace = true }
candid = { workspace = true }
clap = { version = "3.2.6", features = ["derive"] }
dashmap = "5.3.4"
futures = { workspace = true }
hex = "0.4.3"
ic-crypto-utils-basic-sig = { path = "../../crypto/utils/basic_sig" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-client = { path = "../../registry/client" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
ic-registry-local-store = { path = "../../registry/local_store" }
ic-types = { path = "../../types/types" }
lazy_static = "1.4.0"
mockall = "0.11.1"
nix = { workspace = true }
opentelemetry = "0.18.0"
opentelemetry-prometheus = "0.11.0"
prometheus = { workspace = true }
regex = "1.7.1"
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.139", features = ["serde_derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.82"
tokio = { workspace = true }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.11", features = ["json"] }
