[package]
name = "ic-nns-governance-api"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[dependencies]
bytes = { workspace = true }
candid = { workspace = true }
ic-nervous-system-proto = { path = "../../../nervous_system/proto" }
ic-protobuf = { path = "../../../protobuf" }
itertools = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
strum_macros = { workspace = true }
strum = { workspace = true }
comparable = { version = "0.5", features = ["derive"] }
