[package]
name = "ic-crypto-internal-seed"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-crypto-sha2 = { path = "../../../sha2" }
ic-types = { path = "../../../../types/types" }
hex = "0.4"
rand = "0.8"
rand_chacha = "0.3"
serde = { workspace = true }
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }
