repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: no-commit-to-branch
    stages: [commit]
- repo: local
  hooks:
  - id: candid_changes_are_backwards_compatible
    name: Candid changes are backwards compatible
    entry: gitlab-ci/src/checks/candid_changes_are_backwards_compatible.py # TODO: Uncomment (once we figure out how to not cause lots of problems for people): --also-reverse
    # Run against all .did files where the path contains nns or registry.
    files: (nns|registry|sns).+[.]did$
    # Warning: Remember to put the pipe operator at the end of all lines except the last.
    exclude: |
        (?x)^(
            # Is this just test data?
            | rs/nns/empty\.did
        )$
    language: system
    always_run: true

  - id: bazel_buildifier
    name: Auto format bazel build files.
    stages: [commit]
    entry: bazel run //:buildifier
    files: \.bazel|\.bzl$
    language: system

  - id: bazel_smoke
    name: Run all bazel test smoke targets
    entry: bazel test --config=precommit //...
    pass_filenames: false
    language: system
    always_run: true

# The following repo is maintained by us at
# https://gitlab.com/dfinity-lab/open/pre-commit-tools.
- repo: https://gitlab.com/dfinity-lab/open/pre-commit-tools.git
  rev: 17101bf5cebeda988b13764909a6140badc5ef03
  hooks:
  - id: buf-checks
    args: ["--config=buf.yaml"]
    exclude: |
      (?x)(
      )
  - id: shfmt
    args: ["-w", "-i", "4", "-bn", "-ci"]
  - id: nixpkgs-fmt
    exclude: |
        (?x)^(
            .*/Cargo\.nix|
            experimental/.*
        )$
  - id: rustfmt
    exclude: |
        (?x)(
            experimental/|
            rust_canisters/|
            nix/overlays/|
            gitlab-ci/|
            crypto/internal/crypto_lib/fs_ni_dkg/miracl_core
        ) # exclude these directories.

- repo: https://github.com/willthames/ansible-lint.git
  rev: v4.2.0
  hooks:
    - id: ansible-lint
      always_run: false
      files: (^|/)testnet/.+\.(yaml|yml)$
      exclude: |
          (?x)^(
              testnet/tests/.*|.*/docker-compose.yml|testnet/env/shared-config\.yml
          )$
