apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rust-rest-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: rust-rest-service
  endpoints:
  - port: http
    path: /metrics
    interval: 15s