[package]
name = "wasm-api-sys"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[build-dependencies]
bindgen = "0.65.1"
