[package]
name = "ic-nervous-system-proxied-canister-calls-tracker"
version = "0.0.1"
edition = "2021"

[dependencies]
ic-base-types = { path = "../../types/base_types" }

[dev-dependencies]
maplit = "1.0.2"
pretty_assertions = { workspace = true }
tokio = { workspace = true }
