[package]
name = "ic-context-logger"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
