[package]
name = "ic-xnet-hyper-new"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
hyper = { workspace = true }
hyper-rustls = { workspace = true }
hyper-util = { workspace = true }
ic-crypto-tls-interfaces = { path = "../../crypto/tls_interfaces" }
ic-xnet-uri-new = { path = "../uri_new" }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tower = { workspace = true }
