[package]
name = "ic-cketh-minter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ic-cketh-minter"
path = "src/main.rs"

[dependencies]
candid = "0.8.1"
ethnum = { workspace = true }
hex = "0.4"
ic-cdk = "0.7.0"
ic-cdk-macros = "0.6.0"
ic-crypto-ecdsa-secp256k1 = { path = "../../../crypto/ecdsa_secp256k1" }
serde = "1"
serde_json = "1"
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
