[package]
name = "ic-cketh-minter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ic-cketh-minter"
path = "src/main.rs"

[dependencies]
candid = { workspace = true }
ethabi = "18.0.0"
ethnum = { workspace = true }
hex = "0.4"
hex-literal = "0.4.1"
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-crypto-ecdsa-secp256k1 = { path = "../../../crypto/ecdsa_secp256k1" }
ic-crypto-sha3 = { path = "../../../crypto/sha3" }
num-bigint = "0.4.3"
serde = "1"
serde_json = "1"

[dev-dependencies]
assert_matches = "1.5.0"
