[package]
name = "ic-cketh-minter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ic-cketh-minter"
path = "src/main.rs"

[dependencies]
candid = { workspace = true }
ethnum = { workspace = true }
hex = "0.4"
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-crypto-ecdsa-secp256k1 = { path = "../../../crypto/ecdsa_secp256k1" }
serde = "1"
serde_json = "1"
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
