[package]
name = "ic-cketh-minter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ic-cketh-minter"
path = "src/main.rs"

[[bin]]
name = "cketh-principal-to-hex"
path = "bin/principal_to_hex.rs"

[dependencies]
askama = "0.11"
candid = { workspace = true }
ciborium = { workspace = true }
ethnum = { workspace = true }
futures = { workspace = true }
hex = "0.4"
ic-ic00-types = { path = "../../../types/ic00_types" }
hex-literal = "0.4.1"
ic-canister-log = "0.2.0"
ic-canisters-http-types = { path = "../../../rust_canisters/http_types" }
phantom_newtype = { path = "../../../phantom_newtype" }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-crypto-ecdsa-secp256k1 = { path = "../../../crypto/ecdsa_secp256k1" }
ic-crypto-sha3 = { path = "../../../crypto/sha3" }
ic-icrc1-client-cdk = { path = "../../../rosetta-api/icrc1/client/cdk" }
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
ic-metrics-encoder = "1"
rlp = "0.5.2"
num-bigint = "0.4.3"
num-traits = "0.2.14"
minicbor = { workspace = true }
minicbor-derive = { workspace = true }
serde = "1"
serde_json = "1"
serde_bytes = "0.11"
strum = "0.23.0"
strum_macros = "0.23.0"
thousands = "0.2"

[dev-dependencies]
assert_matches = "1.5.0"
ethers-core = "2.0.8"
ic-base-types = { path = "../../../types/base_types" }
ic-config = { path = "../../../config" }
ic-icrc1-ledger = { path = "../../../rosetta-api/icrc1/ledger" }
ic-state-machine-tests = { path = "../../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../../test_utilities/load_wasm" }
proptest = "1.0"
