[package]
name = "bazelifier"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
askama = { version = "0.11.1", features = ["serde-json"] }
clap = { version = "3.1.18", features = ["derive"] }
eyre = "0.6.8"
lazy_static = "1.4.0"
maplit = "1.0.2"
pathdiff = "0.2.1"
semver = { version = "1.0.9", features = ["serde"] }
serde = { workspace = true }
toml = "0.5.9"
