[package]
name = "config"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
ic-types = { path = "../../types/types" }
clap = { workspace = true }
utils = { path = "../utils" }
url = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }
serde_with = "1.6.2"

[dev-dependencies]
once_cell = "1.8"

[lib]
name = "config"
path = "src/lib.rs"

[[bin]]
name = "config"
path = "src/main.rs"
