[package]
name = "ic-registry-node-provider-rewards"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
ic-base-types = { path = "../../types/base_types" }
ic-protobuf = { path = "../../protobuf" }
itertools = { workspace = true }
num-traits = { workspace = true }
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"
ic-management-canister-types = { path = "../../types/management_canister_types" }
