[package]
name = "ic-icos-sev-interfaces"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
async-trait = "0.1.41"
ic-types = { path = "../../types/types" }
thiserror = "1"
tokio = { workspace = true }
