[package]
name = "ic-btc-service"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
prost = "^0.13.1"
tonic = "^0.12.0"

[build-dependencies]
tonic-build = "^0.12.1"
