# Container images used by jobs.

.ic-build-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:cf9b3df4250978164a55132ef1e3714d6e1d2c00e5349f0e964b0e7382a574b8"
.ic-build-bazel-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:cf9b3df4250978164a55132ef1e3714d6e1d2c00e5349f0e964b0e7382a574b8"
