# Container images used by jobs.

.ic-build-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:a45a23e57f9292ad77722209cf47707cec1bf072205717194b4d36d28dbabeee"

.ic-build-nix-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-nix:a45a23e57f9292ad77722209cf47707cec1bf072205717194b4d36d28dbabeee"

.ic-build-bazel-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:a45a23e57f9292ad77722209cf47707cec1bf072205717194b4d36d28dbabeee"
