# Container images used by jobs.

.ic-build-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:4994b5a41a0d4a4fc03d6a32f4c1e91a01e427047261c00e8bea574193cc4a17"

.ic-build-bazel-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:4994b5a41a0d4a4fc03d6a32f4c1e91a01e427047261c00e8bea574193cc4a17"
