# Container images used by jobs.

.ic-build-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-legacy:464ea1da1d0f3803cbce5a73cc766e2be04f4608f419e8eacc8bdcf074078b94"
  tags:
    - dfinity-ic
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME

.ic-build-image-on-docker:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-legacy:464ea1da1d0f3803cbce5a73cc766e2be04f4608f419e8eacc8bdcf074078b94"
  tags:
    - dfinity
    - ubuntu
    - docker

.ic-build-bazel-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:464ea1da1d0f3803cbce5a73cc766e2be04f4608f419e8eacc8bdcf074078b94"
  tags:
    - dfinity-ic
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME
