# Container images used by jobs.

.ic-build-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:75af310773f3628ee55e3879e63a1e588c9a561fd5652c587c4983300270a1ac"

.ic-build-bazel-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:75af310773f3628ee55e3879e63a1e588c9a561fd5652c587c4983300270a1ac"
