# Container images used by jobs.

.ic-build-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:b03121227436cafc09fe02b3fbe0b22eec85438aa53bf024d246cb5ef89084a3"

.ic-build-nix-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-nix:b03121227436cafc09fe02b3fbe0b22eec85438aa53bf024d246cb5ef89084a3"

.ic-build-bazel-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:b03121227436cafc09fe02b3fbe0b22eec85438aa53bf024d246cb5ef89084a3"
