# Container images used by jobs.

.ic-build-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:0b352ab531c2b8d8a5a2c6857a1d65b6f2713b85081f3345d54d19349caf893a"
.ic-build-bazel-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:0b352ab531c2b8d8a5a2c6857a1d65b6f2713b85081f3345d54d19349caf893a"
