# Container images used by jobs.

.ic-build-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-legacy:3007d0eb70df490b2967b4d2cee5f9d21d2acff0eae54103303a2a87c9949d41"
  tags:
    - dfinity-ic
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME

.ic-build-bazel-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:3007d0eb70df490b2967b4d2cee5f9d21d2acff0eae54103303a2a87c9949d41"
  tags:
    - dfinity-ic
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME
