# Container images used by jobs.

.ic-build-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:868769613db7416b133c2d625641ec3f7bc707881498cfc9b7e0fd95bdc3d9c2"
  tags:
    - dfinity-ic
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME

.ic-build-bazel-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:868769613db7416b133c2d625641ec3f7bc707881498cfc9b7e0fd95bdc3d9c2"
  tags:
    - dfinity-ic
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME
