# Container images used by jobs.

.ic-build-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-legacy:b38cc3a226b13bb623cb8fbaa80ec2ca224f84a6107b869837cbbd3b952c6889"
  tags:
    - dfinity-ic
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME

.ic-build-image-on-docker:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-legacy:b38cc3a226b13bb623cb8fbaa80ec2ca224f84a6107b869837cbbd3b952c6889"
  tags:
    - dfinity
    - ubuntu
    - docker

.ic-build-bazel-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:b38cc3a226b13bb623cb8fbaa80ec2ca224f84a6107b869837cbbd3b952c6889"
  tags:
    - dfinity-ic
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME
