# Container images used by jobs.

.ic-build-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:2c239e0252c53a60bd1a28ad6fb6cca7f76b447a69ee5c1efd75ff489cf15c1f"

.ic-build-nix-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-nix:2c239e0252c53a60bd1a28ad6fb6cca7f76b447a69ee5c1efd75ff489cf15c1f"

.ic-build-bazel-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:2c239e0252c53a60bd1a28ad6fb6cca7f76b447a69ee5c1efd75ff489cf15c1f"
