# Container images used by jobs.

.ic-build-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:6e57cc5fbb3f00dc0148ab0d5312369711ff13ace1c01fca54aa0a5ed842dad9"

.ic-build-nix-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-nix:6e57cc5fbb3f00dc0148ab0d5312369711ff13ace1c01fca54aa0a5ed842dad9"

.ic-build-bazel-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:6e57cc5fbb3f00dc0148ab0d5312369711ff13ace1c01fca54aa0a5ed842dad9"
