# Container images used by jobs.

.ic-build-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:8c05cff14fb59e6d95f5abd7a5125b5b537b5f50462f716d8529a1bff378123a"

.ic-build-nix-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-nix:8c05cff14fb59e6d95f5abd7a5125b5b537b5f50462f716d8529a1bff378123a"

.ic-build-bazel-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:8c05cff14fb59e6d95f5abd7a5125b5b537b5f50462f716d8529a1bff378123a"
