# Container images used by jobs.

.ic-build-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:2288083eb7f5cf80f50f5e222457b13c1b37a9a607a114290cb5ed34ad4f530b"

.ic-build-bazel-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:2288083eb7f5cf80f50f5e222457b13c1b37a9a607a114290cb5ed34ad4f530b"
