# Container images used by jobs.

.ic-build-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:e3ddcd45234091e37f96648d4134f60e94eca6026104a7ea34f1b27aa9acb473"

.ic-build-nix-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-nix:e3ddcd45234091e37f96648d4134f60e94eca6026104a7ea34f1b27aa9acb473"

.ic-build-bazel-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:e3ddcd45234091e37f96648d4134f60e94eca6026104a7ea34f1b27aa9acb473"
