# Container images used by jobs.

.ic-build-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-legacy:f8af654ccaf573181b973dde5ac11d15dedbbe24911bc3d2ee4a79b8a40ae888"
  tags:
    - dfinity-ic
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME

.ic-build-image-on-docker:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-legacy:f8af654ccaf573181b973dde5ac11d15dedbbe24911bc3d2ee4a79b8a40ae888"
  tags:
    - dfinity
    - ubuntu
    - docker

.ic-build-bazel-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:f8af654ccaf573181b973dde5ac11d15dedbbe24911bc3d2ee4a79b8a40ae888"
  tags:
    - dfinity-ic
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME
