# Container images used by jobs.

.ic-build-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:4ed8c4a9b1f77d0bdd889199be6e8722b70766035e41f694d52d43137fef7ef1"
  tags:
    - dfinity-ic
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME

.ic-build-legacy-image:
  artifacts:
    expire_in: 3 days
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-legacy:4ed8c4a9b1f77d0bdd889199be6e8722b70766035e41f694d52d43137fef7ef1"
  tags:
    - dfinity-ic
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME
