# Container images used by jobs.

.ic-build-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:e911f0cb1420870b1f4dfe7f20b4570ffa9d92b30937b5a3cab831521571a81c"

.ic-build-nix-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-nix:e911f0cb1420870b1f4dfe7f20b4570ffa9d92b30937b5a3cab831521571a81c"

.ic-build-bazel-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:e911f0cb1420870b1f4dfe7f20b4570ffa9d92b30937b5a3cab831521571a81c"
