include:
- local: /gitlab-ci/config/00--child-pipeline-root.yml

.ubuntu-docker-protected:
  extends:
    - .ubuntu-nix-docker
    - .ic-build-image
  tags:
    - dfinity-launch

.ubuntu-docker-k8s-protected:
  extends:
    - .ubuntu-docker-protected
