# Container images used by jobs.

.ic-build-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:5a5f3be789643be04ee8eb103f75c46fbf3a0296371a4769bd6bc4b76c1d1558"

.ic-build-nix-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-nix:5a5f3be789643be04ee8eb103f75c46fbf3a0296371a4769bd6bc4b76c1d1558"

.ic-build-bazel-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:5a5f3be789643be04ee8eb103f75c46fbf3a0296371a4769bd6bc4b76c1d1558"
