# This file will be included in the child pipeline if there ARE changes in the /rs or /ic-os/guestos folder
#
# - all jobs included transitively from this file (keys not starting with dot) will run.
# - additional `cargo test` jobs will be generated for some crates by `src/gen_gitlab_cargo_pipeline`

include:
- local: /gitlab-ci/config/00--common.yml
- local: /gitlab-ci/config/20--wait-for-parent-pipeline-jobs.yml
- local: /gitlab-ci/config/20--test--build-ic.yml
- local: /gitlab-ci/config/20--test--after-script.yml
- local: /gitlab-ci/config/30--cargo-build--child-pipeline.yml
- local: /gitlab-ci/config/46--guest-os-build--guest-base-image.yml
- local: /gitlab-ci/config/46--rosetta-api-docker-image.yml
- local: /gitlab-ci/config/47--guest-os-test--guest-os-e2e-test.yml
- local: /gitlab-ci/config/54--host-os-test--host-os-upgrade-test.yml
- local: /gitlab-ci/config/55--determinism-test.yml

.cargo-build-docker-protected:
  needs: []  # don't wait on other jobs by default
  extends:
    - .ubuntu-k8s-protected
    - .rules-parent-pipeline
  stage: cargo-build

.cargo-build-docker:
  needs: []  # don't wait on other jobs by default
  extends:
    - .ubuntu-k8s
    - .rules-parent-pipeline
  stage: cargo-build

.cargo-build-macos:
  needs: []  # don't wait on other jobs by default
  extends:
    - .macos-cargo-native
    - .rules-parent-pipeline-protected-branch-only
  stage: cargo-build
