# Container images used by jobs.

.ic-build-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:2e689f7b44ed11c8faaddfb29aafe1eb2c2fc9b1459a8b6870cd6df899a7ef21"

.ic-build-nix-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-nix:2e689f7b44ed11c8faaddfb29aafe1eb2c2fc9b1459a8b6870cd6df899a7ef21"

.ic-build-bazel-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:2e689f7b44ed11c8faaddfb29aafe1eb2c2fc9b1459a8b6870cd6df899a7ef21"
