# Container images used by jobs.

.ic-build-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:b61b9c413cd915a5a01e5d44a4cfaea530a49b7e2b5f7cbfbd21c9469edd5b0e"

.ic-build-nix-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-nix:b61b9c413cd915a5a01e5d44a4cfaea530a49b7e2b5f7cbfbd21c9469edd5b0e"

.ic-build-bazel-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:b61b9c413cd915a5a01e5d44a4cfaea530a49b7e2b5f7cbfbd21c9469edd5b0e"
