no-interrupt:
  extends:
    - .ubuntu-cargo-k8s
    - .rules-any-schedule
  stage: init
  interruptible: False
  script:
    - echo "This pipeline is not interruptible"

cargo-audit:
  extends:
    - .ubuntu-cargo-k8s
    - .rules-cargo-audit-schedule
  stage: init
  script:
    - cd rs; cargo audit
