pre-commit:
  variables:
    # Set the pre-commit home to this directory so we can cache it
    # more easily.
    PRE_COMMIT_HOME: /cache/pre-commit/$CI_CONCURRENT_ID
  extends:
    - .bazel-build-k8s
    - .bazel-rules-pipeline
  needs: []  # don't wait on other jobs
  tags:
    - dfinity-ic # overwritting so we do not inherit the zh tag
  stage: test
  script:
    - |
      set -eEuo pipefail

      rustup default stable

      # Make sure CI can pull from the private repo.
      if ! pre-commit run -a --hook-stage=manual ; then
        echo "Pre-commit checks failed. Here is the diff of the changes:"
        git diff
        echo
        echo "You can fix the code locally by following these instructions in the same branch."
        echo
        echo "install pre-commit by following https://pre-commit.com/#installation:"
        echo "(brew|pip) install pre-commit"
        echo "pre-commit install"
        echo
        echo "Then, to fix the checks in this branch, run:"
        echo "pre-commit run --from-ref=\$(git merge-base HEAD master) --to-ref=HEAD"
        echo
        echo "And then commit the changes."
        exit 1
      fi
