gen-cargo-pipeline:
  extends:
    - .ubuntu-cargo-docker-k8s
    - .cargo-rules-autorun-on-trigger
  # Child pipeline must be generated in a stage prior to the one where it runs
  stage: init
  tags:
    - dfinity
    - ubuntu
  variables:
    PYTHONPATH : ${CI_PROJECT_DIR}/gitlab-ci/src
  script:
    - |
      set -euo pipefail
      ssh-add -L

      cd gitlab-ci/src/
      $SHELL_WRAPPER python3 gen_gitlab_cargo_pipeline/gen_pipeline.py \
        ../../ ../../ic-os -v --out=../../child-pipeline.yml
      
      cd -

  artifacts:
    paths:
      - child-pipeline.yml
    reports:
      dotenv: dc.env

cargo-pipeline:
  extends: .cargo-rules-autorun-on-trigger
  stage: test
  needs:
    - job: gen-cargo-pipeline
    - job: container-autobuild-protected
      optional: true
  variables:
    CI_PARENT_PIPELINE_SOURCE: "${CI_PIPELINE_SOURCE}"
  trigger:
    include:
      - artifact: child-pipeline.yml
        job: gen-cargo-pipeline
    strategy: depend
