.docker-build-ic:
  extends:
    - .ubuntu-nix-docker
  needs: []
  stage: test
  artifacts:
    reports:
      dotenv: nns.release.env
    paths:
      - bazel-build-log*.json*
  script:
    - |
      set -euo pipefail
      VERSION=$(git rev-parse HEAD)

      if [ "$CI_JOB_NAME" != "docker-build-ic" ]; then
          # read NNS release version from git tree
          NNS_RELEASE_VERSION="$(jq -r '.subnets["tdb26-jop6k-aogll-7ltgs-eruif-6kk7m-qpktf-gdiqx-mxtrf-vb5e6-eqe"]' testnet/mainnet_revisions.json)"
          # we pass nss version info to build-determinism-*-release jobs
          # we put it under /tmp due to git clean -ffdx within docker-build-ic script
          echo "NNS_RELEASE_VERSION=$NNS_RELEASE_VERSION" > /tmp/nns.release.env

          # fetch and checkout this version
          git fetch origin "$NNS_RELEASE_VERSION"
          git checkout "$NNS_RELEASE_VERSION"
          # NOTE: ic/$VERSION in S3 will have artifacts
          #       for revision $NNS_RELEASE_VERSION !!!
      fi

      # run docker-build-ic
      gitlab-ci/tools/docker-build-ic

      # generate SHA256SUMS files
      cd artifacts/docker-build-ic/release
      GLOBIGNORE="SHA256SUMS"
      echo "Binaries SHA256SUMS"
      # shellcheck disable=SC2035
      sha256sum -b *.gz | tee SHA256SUMS
      cd ../canisters
      echo "Canisters SHA256SUMS"
      # shellcheck disable=SC2035
      sha256sum -b *.gz | tee SHA256SUMS
      cd ../icos
      echo "IC-OS SHA256SUMS"
      # shellcheck disable=SC2035
      sha256sum -b *.tar.* | tee SHA256SUMS
      cd ../../..

      # release binaries
      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
          "artifacts/docker-build-ic/release" "${CI_JOB_NAME}/release"
      # canister binaries
      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
          "artifacts/docker-build-ic/canisters" "${CI_JOB_NAME}/canisters"
      # ic-os update img
      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
          "artifacts/docker-build-ic/icos" "${CI_JOB_NAME}/guest-os/update-img"

      # collect dotenv
      if [ -f /tmp/nns.release.env ]; then
          mv /tmp/nns.release.env .
      fi

# MR Pipeline
docker-build-ic:
  extends:
    - .docker-build-ic
    - .rules-parent-pipeline

# Scheduled Pipeline
docker-build-ic-release:
  extends:
    - .docker-build-ic
    - .rules-scheduled-reproducibility
