.build-ic:
  extends:
    - .ic-build-bazel-image
  needs: []
  stage: test
  artifacts:
    reports:
      dotenv: nns.release.env
    paths:
      - bazel-build-log*.json*
  script:
    - |
      set -euo pipefail
      VERSION=$(git rev-parse HEAD)

      if [ "$CI_JOB_NAME" == "build-ic-release" ]; then
          # read NNS release version from git tree
          NNS_RELEASE_VERSION="$(jq -r '.subnets["tdb26-jop6k-aogll-7ltgs-eruif-6kk7m-qpktf-gdiqx-mxtrf-vb5e6-eqe"]' testnet/mainnet_revisions.json)"
          # we pass nss version info to build-determinism-*-release jobs
          # we put it under /tmp due to git clean -ffdx within build-ic script
          echo "NNS_RELEASE_VERSION=$NNS_RELEASE_VERSION" > /tmp/nns.release.env

          # fetch and checkout this version
          git fetch origin "$NNS_RELEASE_VERSION"
          git checkout "$NNS_RELEASE_VERSION"
          # NOTE: ic/$VERSION in S3 will have artifacts
          #       for revision $NNS_RELEASE_VERSION !!!
      fi

      PATH_PREFIX="artifacts/"
      # depending on revision, we use docker or podman
      if [ -e gitlab-ci/container/build-ic.sh ]; then
          # run build-ic (podman)
          gitlab-ci/container/build-ic.sh -i -c -b
      else
          # run docker-build-ic (docker)
          gitlab-ci/tools/docker-build-ic
          PATH_PREFIX="artifacts/docker-build-ic/"

          # generate SHA256SUMS files
          cd artifacts/docker-build-ic/release
          GLOBIGNORE="SHA256SUMS"
          echo "Binaries SHA256SUMS"
          # shellcheck disable=SC2035
          sha256sum -b *.gz | tee SHA256SUMS
          cd ../canisters
          echo "Canisters SHA256SUMS"
          # shellcheck disable=SC2035
          sha256sum -b *.gz | tee SHA256SUMS
          cd ../icos
          echo "IC-OS SHA256SUMS"
          # shellcheck disable=SC2035
          sha256sum -b *.tar.* | tee SHA256SUMS
          cd ../../..
      fi

      # release binaries
      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
          "${PATH_PREFIX}/release" "${CI_JOB_NAME}/release"
      # canister binaries
      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
          "${PATH_PREFIX}/canisters" "${CI_JOB_NAME}/canisters"
      # ic-os update img
      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
          "${PATH_PREFIX}/icos" "${CI_JOB_NAME}/guest-os/update-img"

      # collect dotenv
      if [ -f /tmp/nns.release.env ]; then
          mv /tmp/nns.release.env .
      fi

# MR Pipeline
build-ic:
  tags:
    - k8s
    - dfinity
  extends:
    - .build-ic
    - .rules-parent-pipeline

# Scheduled Pipeline
build-ic-release:
  tags:
    # TODO: IDX-2625
    - docker
    - dfinity
  extends:
    - .build-ic
    - .rules-scheduled-reproducibility
