gitlab-ci-config-validation:
  extends:
    - .ubuntu-k8s
    - .rules-pipeline-no-merge-train
  stage: test
  variables:
    PYTHONPATH : "${CI_PROJECT_DIR}/gitlab-ci/src:${CI_PROJECT_DIR}/gitlab-ci/src/dependencies"
  artifacts:
    reports:
      junit: test_report.xml
    paths:
      - gitlab-ci/src/htmlcov
  script:
    - |
      set -xeuo pipefail
      cd gitlab-ci/src
      python3 gitlab_config/main.py --cfg-validate

python-gitlab-ci-tests:
  extends:
    - .ubuntu-k8s
    - .rules-pipeline-no-merge-train
  needs: []
  stage: test
  variables:
    PYTHONPATH : "${CI_PROJECT_DIR}/gitlab-ci/src:${CI_PROJECT_DIR}/gitlab-ci/src/dependencies"
  artifacts:
    reports:
      junit: test_report.xml
    paths:
      - gitlab-ci/src/htmlcov
  script:
    - |
      set -xeuo pipefail
      cd gitlab-ci/src
      pytest -v -o junit_family=xunit1 --junitxml=../../test_report.xml --cov=. --cov-report=term --cov-report=term-missing --cov-report=html --cov-branch
