python-tests:
  allow_failure: true # TODO(IDX-2629) remove when fixed.
  extends:
    - .ubuntu-docker-k8s
    - .rules-pipeline-no-merge-train
  needs:
    # Some tests download canisters from the s3 - it has to only run when all canisters were uploaded to not populate proxy cache with partial results.
    job: bazel-test-all
    artifacts: false
  stage: test
  variables: 
    PYTHONPATH : ${CI_PROJECT_DIR}/gitlab-ci/src
  artifacts:
    reports:
      junit: test_report.xml
    paths:
      - gitlab-ci/src/htmlcov
  script:
    - |
      set -xeuo pipefail
      cd gitlab-ci/src
      pytest -v -o junit_family=xunit1 --junitxml=../../test_report.xml --cov=. --cov-report=term --cov-report=term-missing --cov-report=html --cov-branch --ignore=simple_prober
      python3 gitlab_config/main.py --job-list-validate
      python3 gitlab_config/main.py --cfg-validate
    - |
      echo "Running scalability/common/tests"
      set -euo pipefail
      cd "${CI_PROJECT_DIR}/scalability"
      pipenv --python 3
      pipenv install -r requirements.txt
      for test_file in common/tests/*.py; do { $SHELL_WRAPPER pipenv run python3 -m unittest "$test_file"; } done
