cargo-clippy-linux:
  extends: .cargo-build-docker
  variables:
    BUILD_COMMAND: "$CI_PROJECT_DIR/gitlab-ci/src/rust_lint/lint.sh"

# Cargo is deprecated and will be replaced with Bazel.
# Until the migration is complete, run a simple check for build failures.
legacy-cargo-check:
  extends: .cargo-build-docker
  variables:
    BUILD_COMMAND: "cargo check --tests --benches"

cargo-build-release-linux:
  extends: 
  - .cargo-build-docker
  - .rules-parent-pipeline-protected-branch-only
  artifacts:
    paths:
      - artifacts/nix-release/*
  variables:
    BUILD_COMMAND: "cargo build --release"
  # TODO(IDX-2581): Remove "allowed to fail" when build fixed
  allow_failure: true
