cargo-clippy-linux:
  extends: .cargo-build-docker
  variables:
    BUILD_COMMAND: "$CI_PROJECT_DIR/gitlab-ci/src/rust_lint/lint.sh"

cargo-clippy-darwin:
  extends:
    - .cargo-build-macos
  variables:
    BUILD_COMMAND: "$CI_PROJECT_DIR/gitlab-ci/src/rust_lint/lint.sh"

cargo-build-debug-linux:
  extends: .cargo-build-docker
  variables:
    BUILD_COMMAND: "cargo build"

cargo-build-debug-darwin:
  extends: .cargo-build-macos
  variables:
    BUILD_COMMAND: "cargo build"

# Warning! If you rename this job, you update ALL `gitlab-artifacts-download` invocations.
cargo-build-release-linux:
  extends: 
  - .cargo-build-docker
  - .rules-parent-pipeline-protected-branch-only
  artifacts:
    paths:
      - artifacts/nix-release/*
  variables:
    BUILD_COMMAND: "cargo build --release"

cargo-build-release-darwin:
  extends: .cargo-build-macos
  artifacts:
    paths:
      - artifacts/nix-release/*
  variables:
    BUILD_COMMAND: "cargo build --release"
    BUILD_COMMAND_POST: "cd ${CI_PROJECT_DIR}/gitlab-ci/src && python3 -m artifacts.collect_build_binaries artifacts/nix-release; cd ${CI_PROJECT_DIR} && gitlab-ci/src/artifacts/rclone_upload.py --version='$CI_COMMIT_SHA' 'artifacts/nix-release' nix-release/x86_64-darwin"

cargo-build-release-linux-native:
  extends:
    - .cargo-build-docker-protected
    - .rules-parent-pipeline-autorun-on-trigger
  image:
    # Use the docker image without nix-shell
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:7e58156e2f6210633b9c55a5ddfc66416ffbfd72b113ac912dd1894add0c85fa"
  variables:
    ARTIFACT_EXT: ""
  artifacts:
    paths:
      - "artifacts/release${ARTIFACT_EXT}/*"
      - bazel-build-log*.json*
  script:
    - |
      "${CI_PROJECT_DIR}/gitlab-ci/tools/job-driver.py" "${CI_JOB_NAME}"

      cd "${CI_PROJECT_DIR}"
      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
        gitlab-ci/src/artifacts/rclone_upload.py --version="$CI_COMMIT_SHA" \
        "artifacts/release${ARTIFACT_EXT}" "release${ARTIFACT_EXT}"

cargo-build-release-linux-native-malicious:
  extends: cargo-build-release-linux-native
  variables:
    ARTIFACT_EXT: "-malicious"

cargo-build-canisters:
  extends:
    - .cargo-build-docker-protected
    - .rules-parent-pipeline-autorun-on-trigger
  variables:
    ARTIFACT_EXT: ""
  image:
    # Use the docker image without nix-shell
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:7e58156e2f6210633b9c55a5ddfc66416ffbfd72b113ac912dd1894add0c85fa"
  artifacts:
    paths:
      - "artifacts/canisters${ARTIFACT_EXT}/*"
  script:
    - |
      "${CI_PROJECT_DIR}/gitlab-ci/tools/job-driver.py" "${CI_JOB_NAME}"

      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
        gitlab-ci/src/artifacts/rclone_upload.py --version="$CI_COMMIT_SHA" \
        "artifacts/canisters${ARTIFACT_EXT}" "canisters${ARTIFACT_EXT}"

dfx-build-release-darwin:
  extends: .cargo-build-macos
  artifacts:
    paths:
      - artifacts/sdk-release/*
  variables:
    BUILD_COMMAND: "${CI_PROJECT_DIR}/gitlab-ci/tools/build-dfx-binaries"
    BUILD_COMMAND_POST: "cd ${CI_PROJECT_DIR}/gitlab-ci/src && python3 -m artifacts.collect_build_binaries artifacts/sdk-release/x86_64-darwin; cd ${CI_PROJECT_DIR} && gitlab-ci/src/artifacts/rclone_upload.py --version='$CI_COMMIT_SHA' 'artifacts/sdk-release' sdk-release"

dfx-build-release-linux:
  extends:
    - .cargo-build-docker-protected
    - .rules-parent-pipeline-autorun-on-trigger
  artifacts:
    paths:
      - artifacts/sdk-release/*
  image:
    # Use the docker image without nix-shell
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:7e58156e2f6210633b9c55a5ddfc66416ffbfd72b113ac912dd1894add0c85fa"
  variables:
    BUILD_COMMAND: ""
    CARGO_BUILD_TARGET: x86_64-unknown-linux-gnu
    OPENSSL_INCLUDE_DIR: /usr/include/x86_64-linux-gnu
    OPENSSL_LIB_DIR: /usr/lib/x86_64-linux-gnu
    OPENSSL_STATIC: "1"
  script:
    - |
      set -eExuo pipefail

      # the pkg-config crate ignores requests to link statically if a dylib is available
      sudo rm /usr/lib/x86_64-linux-gnu/liblmdb.so*

      "${CI_PROJECT_DIR}/gitlab-ci/tools/build-dfx-binaries"

      pushd "${CI_PROJECT_DIR}/gitlab-ci/src"
      python3 -m artifacts.collect_build_binaries artifacts/sdk-release/x86_64-linux
      popd

      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
        gitlab-ci/src/artifacts/rclone_upload.py --version="$CI_COMMIT_SHA" "artifacts/sdk-release" sdk-release
