cargo-clippy-linux:
  extends: .cargo-build-docker
  variables:
    CARGO_BUILD_TARGET: "x86_64-unknown-linux-gnu"
  script:
    - |
      set -eExuo pipefail
      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" build-command -- \
          "$CI_PROJECT_DIR"/gitlab-ci/src/rust_lint/lint.sh

# Cargo is deprecated and will be replaced with Bazel.
# Until the migration is complete, run a simple check for build failures.
legacy-cargo-check:
  extends: .cargo-build-docker
  script:
    - |
      set -eExuo pipefail
      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" build-command -- cargo check --tests --benches

cargo-build-release-linux:
  extends:
  - .cargo-build-docker
  script:
    - |
      set -eExuo pipefail
      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" build-command -- cargo build --release
