legacy-system-tests:
  extends:
    - .ubuntu-nix-docker-pinned-dc
    - .rules-parent-pipeline
  # System tests are very flaky due to replica non-determinism.
  retry: 2
  stage: cargo-test
  needs:
    - job: cargo-build-canisters
      artifacts: false
    - job: cargo-build-release-linux-native
      artifacts: false
    - job: cargo-build-release-linux-native-malicious
      artifacts: false
  artifacts:
    paths:
      - replica-logs/
      - junit_data/
      - coredumps/
      - test-results.json
    when: always
    expire_in: 1 week
    reports:
      junit: test_report.xml
  variables:
      BLOCKING: "blocking"
      TEST_RUNNER_ARGS: "--experimental --jobs 6 --timeout 720s --ready-timeout 90s --result-file ${CI_PROJECT_DIR}/test-results.json --tee-replica-logs-base-dir ${CI_PROJECT_DIR}/replica-logs --skip staging -v"
      RUST_BACKTRACE: 1
  script:
    - |
      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py \
          --git-rev="$CI_COMMIT_SHA" --remote-path="release" \
          --out="artifacts/release"
      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py \
          --git-rev="$CI_COMMIT_SHA" --remote-path="release-malicious" \
          --out="artifacts/release-malicious"
      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py \
          --git-rev="$CI_COMMIT_SHA" --remote-path="canisters" \
          --out="artifacts/canisters"
      "${CI_PROJECT_DIR}/gitlab-ci/src/job_scripts/system-tests.sh"

check-bins-linux:
  extends:
    - .ubuntu-nix-docker-pinned-dc
    - .rules-parent-pipeline
  stage: cargo-test
  needs:
    - job: dfx-build-release-linux
      artifacts: false
  image:
    # 21.04
    name: ubuntu@sha256:b5a61709a9a44284d88fb12e5c48db0409cfad5b69d4ff8224077c57302df9cf
  before_script: /bin/true
  after_script: /bin/true
  variables:
    ARTIFACT_PREFIX: sdk-release/x86_64-linux
  script:
    - |
      set -exuo pipefail

      apt-get update && apt-get install --yes --no-install-recommends curl ca-certificates

      "$CI_PROJECT_DIR"/gitlab-ci/tools/download "${ARTIFACT_PREFIX}/replica.gz" | gunzip > /tmp/replica
      chmod +x /tmp/replica
      ldd /tmp/replica
      /tmp/replica --print-sample-config --replica-version 1 >/dev/null

      "$CI_PROJECT_DIR"/gitlab-ci/tools/download "${ARTIFACT_PREFIX}/ic-starter.gz" | gunzip > /tmp/ic-starter
      chmod +x /tmp/ic-starter
      ldd /tmp/ic-starter
      /tmp/ic-starter --version

check-bins-darwin:
  extends:
    - .rules-parent-pipeline-protected-branch-only
  stage: cargo-test
  needs:
    - job: dfx-build-release-darwin
      artifacts: false
  tags:
    - dfinity
    - macos
  before_script: /usr/bin/true
  after_script: /usr/bin/true
  variables:
    ARTIFACT_PREFIX: sdk-release/x86_64-darwin
    # https://curl.se/mail/lib-2020-06/0010.html
    CURL_SSL_BACKEND: secure-transport
  script:
    - |
      set -exuo pipefail

      "$CI_PROJECT_DIR"/gitlab-ci/tools/download "${ARTIFACT_PREFIX}/replica.gz" | gunzip > /tmp/replica
      chmod +x /tmp/replica
      otool -L /tmp/replica
      /tmp/replica --print-sample-config --replica-version 1 >/dev/null

      "$CI_PROJECT_DIR"/gitlab-ci/tools/download "${ARTIFACT_PREFIX}/ic-starter.gz" | gunzip > /tmp/ic-starter
      chmod +x /tmp/ic-starter
      otool -L /tmp/ic-starter
      /tmp/ic-starter --version

ic-p8s-sd-e2e-test:
  extends:
    - .ubuntu-nix-docker-pinned-dc
    - .rules-parent-pipeline
  needs:
    - cargo-build-release-linux-native
  stage: cargo-test
  script:
    - |
      $SHELL_WRAPPER python3 "${CI_PROJECT_DIR}"/rs/ic_p8s_service_discovery/tests/e2e-test.py
