generic-guest-os-diskimg:
  extends:
    - .ubuntu-docker-k8s-protected
    - .rules-parent-pipeline-autorun-on-trigger
  stage: guest-os-build
  needs:
    - job: cargo-build-release-linux-native
      artifacts: false
  script:
    - |
      set -xeuo pipefail

      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py \
          --git-rev="$CI_COMMIT_SHA" --remote-path="release" \
          --out="artifacts/release"

      pushd artifacts/release
      gunzip \
        boundary-node-control-plane.gz \
        boundary-node-prober.gz \
        denylist-updater.gz \
        ic-balance-exporter.gz \
        ic-registry-replicator.gz
      popd

      cd ic-os/generic-guestos

      mkdir -p build-out/disk-img/ build-tmp/
      buildevents cmd  "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" build-disk-img -- \
      ./scripts/build-disk-image.sh -o build-tmp/disk.img -p root -v "$CI_COMMIT_SHA" -x ../../artifacts/release/
      echo "$CI_COMMIT_SHA" > build-tmp/version.txt
      ls -lah build-tmp

      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" tar-build-out -- tar --sort=name --owner=root:0 --group=root:0 --mtime 0 --sparse -cvzf build-out/disk-img/disk-img.tar.gz -C build-tmp disk.img version.txt
      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" tar-build-out -- tar --sort=name --owner=root:0 --group=root:0 --mtime 0 --sparse -cvf build-out/disk-img/disk-img.tar.zst --use-compress-program="zstd --threads=0 -10" -C build-tmp disk.img version.txt
      ls -lah build-out

      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/openssl-sign.sh "build-out/disk-img"

      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
        "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_upload.py --version="$CI_COMMIT_SHA" build-out/disk-img/ generic-guest-os/disk-img

  artifacts:
    paths:
      - ic-os/generic-guestos/build-out/disk-img/*
    expire_in: 2 days
