deploy-guest-os-baseimg:
  extends:
    - .ubuntu-docker
    - .rules-build-base-images-schedule
  stage: guest-os-build
  needs: []
  script:
   - |
    set -euo pipefail

    TAG=$(date '+%Y-%m-%d-%H%M')

    docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    cd "${CI_PROJECT_DIR}/ic-os/guestos/rootfs"
    docker build -q -t dfinity/guestos-base:"$TAG" -t dfinity/guestos-base:latest -f Dockerfile.base .
    docker push dfinity/guestos-base:"$TAG"
    docker build -q -t dfinity/guestos-base-dev:"$TAG" -t dfinity/guestos-base-dev:latest --build-arg PACKAGE_FILES="packages.common packages.dev" -f Dockerfile.base .
    docker push dfinity/guestos-base-dev:"$TAG"

    cd "${CI_PROJECT_DIR}/ic-os/generic-guestos/rootfs"
    docker build -q -t dfinity/genericos-base:"$TAG" -t dfinity/genericos-base:latest -f Dockerfile.base .
    docker push dfinity/genericos-base:"$TAG"

    cd "${CI_PROJECT_DIR}/ic-os/boundary-guestos/rootfs"
    docker build -q -t dfinity/boundaryos-base:"$TAG" -t dfinity/boundaryos-base:latest -f Dockerfile.base .
    docker push dfinity/boundaryos-base:"$TAG"

    cd "${CI_PROJECT_DIR}/ic-os/boundary-guestos/rootfs"
    docker build -q -t dfinity/boundaryos-base-snp:"$TAG" -t dfinity/boundaryos-base-snp:latest --build-arg CPU_SUPPORT="snp" -f Dockerfile.base .
    docker push dfinity/boundaryos-base-snp:"$TAG"

    echo "Use the image with it's SHA256 DIGEST below for IC-OS Dockerfile"
    docker inspect --format='{{index .RepoDigests 0}}' dfinity/guestos-base:"$TAG"
    echo "Use the image with it's SHA256 DIGEST below for IC-OS Dockerfile (dev version)"
    docker inspect --format='{{index .RepoDigests 0}}' dfinity/guestos-base-dev:"$TAG"
    echo "Use the image with it's SHA256 DIGEST below for GENERIC IC-OS Dockerfile"
    docker inspect --format='{{index .RepoDigests 0}}' dfinity/genericos-base:"$TAG"
    echo "Use the image with it's SHA256 DIGEST below for BOUNDARY IC-OS Dockerfile"
    docker inspect --format='{{index .RepoDigests 0}}' dfinity/boundaryos-base:"$TAG"
    echo "Use the image with it's SHA256 DIGEST below for BOUNDARY IC-OS Dockerfile (snp version)"
    docker inspect --format='{{index .RepoDigests 0}}' dfinity/boundaryos-base-snp:"$TAG"

    IMAGE_LIST=(
        dfinity/guestos-base
        dfinity/guestos-base-dev
        dfinity/genericos-base
        dfinity/boundaryos-base
        dfinity/boundaryos-base-snp
    )
    for IMAGE in IMAGE_LIST; do
      OLD_REF="$(rg -IN '${IMAGE}@sha256:[0-9a-z]{64}' | head -1)"
      NEW_REF="$(docker inspect --format='{{index .RepoDigests 0}}' ${IMAGE}:${TAG})"
      rg -IN "$OLD_REF" --files-with-matches | xargs sed -i 's/$OLD_REF/$NEW_REF/b'
    done
    git status
    git diff
    # TODO: create a MR with updated references

build-guest-os-baseimg:
  extends:
    - .ubuntu-nix-docker
    - .rules-dockerfile-base-changes
  stage: guest-os-build
  needs: []
  script:
  - |
    set -euo pipefail

    TAG=$(date '+%Y-%m-%d-%H%M')
    cd "${CI_PROJECT_DIR}/ic-os/guestos/rootfs"
    docker build -t dfinity/guestos-base:"$TAG" -t dfinity/guestos-base:latest -f Dockerfile.base .
    docker build -t dfinity/guestos-base-dev:"$TAG" -t dfinity/guestos-base-dev:latest --build-arg PACKAGE_FILES="packages.common packages.dev" -f Dockerfile.base .

    cd "${CI_PROJECT_DIR}/ic-os/generic-guestos/rootfs"
    docker build -t dfinity/genericos-base:"$TAG" -t dfinity/genericos-base:latest -f Dockerfile.base .

    cd "${CI_PROJECT_DIR}/ic-os/boundary-guestos/rootfs"
    docker build -t dfinity/boundaryos-base:"$TAG" -t dfinity/boundaryos-base:latest -f Dockerfile.base .
    docker build -t dfinity/boundaryos-base-snp:"$TAG" -t dfinity/boundaryos-base-snp:latest --build-arg CPU_SUPPORT="snp" -f Dockerfile.base .
