.e2e-test-base:
  extends:
    - .ubuntu-k8s
    - .rules-parent-pipeline
  stage: guest-os-test
  retry: 2
  # The e2e tests are flaky and impacting developer merges
  # https://dfinity.slack.com/archives/C012RDFNK7U/p1618233620112900
  variables:
    GUEST_OS_TEST_TIMEOUT: 2400
    # This var is needed as some shell scripts depend on it.
    E2E_TEST_TIMEOUT: 480

.with-monitoring:
  variables:
    # we need debug-level logs from the following components for IC policy monitoring
    REPLICA_LOG_DEBUG_OVERRIDES: "ic_consensus::consensus::batch_delivery,ic_artifact_manager::processors,ic_consensus::consensus,ic_transport::control_plane"
