.e2e-test-base:
  extends:
    - .ubuntu-k8s
    - .rules-parent-pipeline
  stage: guest-os-test
  retry: 2
  # The e2e tests are flaky and impacting developer merges
  # https://dfinity.slack.com/archives/C012RDFNK7U/p1618233620112900
  variables:
    GUEST_OS_TEST_TIMEOUT: 2400
    # This var is needed as some shell scripts depend on it.
    E2E_TEST_TIMEOUT: 480

.with-monitoring:
  variables:
    # we need debug-level logs from the following components for IC policy monitoring
    REPLICA_LOG_DEBUG_OVERRIDES: "ic_consensus::consensus::batch_delivery,ic_artifact_manager::processors,ic_consensus::consensus,ic_transport::control_plane"

.build-and-test-monpoly-docker-e2e: &build-and-test-monpoly-docker-e2e |
  # build monpoly_pipeline container image
  docker build --build-arg MONPOLY_PIPELINE_GIT_REVISION="${CI_COMMIT_SHA}" -t monpoly_pipeline:"${CI_COMMIT_SHA}" ./policy-monitoring

  TEST_DRIVER_ARTIFACTS="${CI_PROJECT_DIR}/working_dir"
  echo "=== Listing contents of ${TEST_DRIVER_ARTIFACTS} ==="
  find "${TEST_DRIVER_ARTIFACTS}" -type d -printf '%d\t%P\n' | sort -nk1 | cut -f2-

  # run monpoly_pipeline docker container with timeout 360 seconds
  MONPOLY_DID=$(docker run -d -it --rm monpoly_pipeline:"${CI_COMMIT_SHA}" "sleep 360")
  docker cp "${TEST_DRIVER_ARTIFACTS}" "${MONPOLY_DID}":/work/system_tests_working_dir
  docker exec "${MONPOLY_DID}" python3 -m tests.monpoly_io
  docker exec "${MONPOLY_DID}" python3 -m tests.mfotl_sanity
  docker exec "${MONPOLY_DID}" ls -alh /work
  docker exec "${MONPOLY_DID}" python3 main.py --fail \
    --system_tests_working_dir /work/system_tests_working_dir --mode universal_policy pre_processor_test

  # clean the container
  docker rm -f "${MONPOLY_DID}"
