host-os-updateimg:
  extends:
    - .ubuntu-docker-k8s-protected
    - .rules-parent-pipeline-autorun-on-trigger
    - .rules-hostos
  stage: host-os-build
  needs: []
  variables:
      BUILD_EXTRA_ARGS: ""
      BUILD_EXTRA_SUFFIX: ""
      POLLUTE_PERMISSIONS: ""
  script:
    - |
      set -xeuo pipefail

      BUILD_OUT="build-out/update-img${BUILD_EXTRA_SUFFIX}"
      BUILD_TMP="build-tmp${BUILD_EXTRA_SUFFIX}"
      UPLOAD_TARGET="host-os/update-img${BUILD_EXTRA_SUFFIX}"
      VERSION=$(git rev-parse HEAD)
      echo "Build ID: ${VERSION}"

      # set permissions to 777 to test if reproducibility is affected
      # we compare images we get from:
      # - host-os-updateimg
      # - host-os-updateimg-determinism
      # see CI job: build-determinism-host-update-img
      if [ "$CI_JOB_NAME" == "host-os-updateimg" ]; then
        chmod -R 777 ic-os/hostos/rootfs/
      fi

      cd "${CI_PROJECT_DIR}"/ic-os/hostos

      mkdir -p "$BUILD_OUT" "$BUILD_TMP"

      if [ "${POLLUTE_PERMISSIONS}" != "" ]; then
          chmod -R 777 rootfs
      fi

      echo "$VERSION" >"${BUILD_TMP}/version.txt"
      echo "${VERSION}" >"rootfs/opt/ic/share/version.txt"
      echo "${VERSION}" >"rootfs/boot/version.txt"

      BASE_IMAGE=$(cat "rootfs/docker-base.prod")
      ../scripts/build-docker-save.sh \
          --build-arg BASE_IMAGE="${BASE_IMAGE}" \
          ./rootfs >$BUILD_TMP/rootfs.tar

      ../scripts/build-update-image.sh -o "${BUILD_OUT}/host-update-img.tar.gz" -i $BUILD_TMP/rootfs.tar "$BUILD_EXTRA_ARGS"

      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/openssl-sign.sh "$BUILD_OUT"

      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" rclone -- \
      "${CI_PROJECT_DIR}"/gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" "$BUILD_OUT" "$UPLOAD_TARGET"

# An exact dupe of the updateimg job for non-determinism testing.
host-os-updateimg-determinism:
  extends:
    - host-os-updateimg
  variables:
      BUILD_EXTRA_ARGS: ""
      BUILD_EXTRA_SUFFIX: "-determinism"
      POLLUTE_PERMISSIONS: "true"
