host-os-diskimg:
  extends:
    - .ubuntu-docker-k8s-protected
    - .rules-parent-pipeline-autorun-on-trigger
    - .rules-hostos
  stage: host-os-build
  needs: []
  artifacts:
    paths:
      - ic-os/hostos/build-out/disk-img${BUILD_EXTRA_SUFFIX}/*
  variables:
      BUILD_EXTRA_SUFFIX: ""
  script:
    - |
      set -xeuo pipefail

      BUILD_OUT="build-out/disk-img${BUILD_EXTRA_SUFFIX}"
      BUILD_TMP="build-tmp${BUILD_EXTRA_SUFFIX}"
      UPLOAD_TARGET="host-os/disk-img${BUILD_EXTRA_SUFFIX}"
      VERSION=$(git rev-parse HEAD)
      export VERSION
      echo "Build ID: ${VERSION}"

      cd "${CI_PROJECT_DIR}"/ic-os/hostos

      mkdir -p "$BUILD_OUT" "$BUILD_TMP"
      echo "$VERSION" >"${BUILD_TMP}/version.txt"

      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" build-disk-img -- \
          ./build.sh -v "$VERSION"
      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" move-build -- \
          tar xzf disk-img.tar.gz -C "$BUILD_TMP"
      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" tar-build-out -- \
          tar --sort=name --owner=root:0 --group=root:0 --mtime='UTC 2020-01-01' --sparse \
          -cvzf "${BUILD_OUT}/disk-img.tar.gz" -C "$BUILD_TMP" disk.img version.txt
      ls -lah "$BUILD_TMP"

      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/openssl-sign.sh "$BUILD_OUT"

      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" rclone -- \
      "${CI_PROJECT_DIR}"/gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" "$BUILD_OUT" "$UPLOAD_TARGET"
