host-os-upgrade-test:
  extends:
    - .ubuntu-k8s-protected
    - .rules-parent-pipeline-autorun-on-trigger
  stage: host-os-test
  rules:
    - if: '$CI_PARENT_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - 'ic-os/**/*'
        - 'toolchains/sysimage/**/*'
        - 'testnet/**/*'
    - if: '$CI_PARENT_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
      allow_failure: true
    - if: '$SCHEDULE_NAME == "run-all-master"'
    - if: '$CI_COMMIT_BRANCH =~ /^rc--/'
  variables:
    HOST_OS_TEST_TIMEOUT: 2400
    # This var is needed as some shell scripts depend on it.
    E2E_TEST_TIMEOUT: 480
  # This test runs VMs on the CI runner, which can be unreliable and slow. This
  # test is soon to be replaced with Farm tests: NODE-565
  needs:
    - job: wait-for-bazel-test-all
      artifacts: false
  artifacts:
    paths:
    - ic-os/hostos/test-out
  script:
    - |
      VERSION=$(git rev-parse HEAD)
      export VERSION

      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py \
          --git-rev="${VERSION}" --remote-path="host-os/disk-img" \
          --out="ic-os/hostos/build-out/disk-img"

      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py \
          --git-rev="${VERSION}" --remote-path="host-os/update-img-dev" \
          --out="ic-os/hostos/build-out/update-img"

      # shellcheck disable=SC2154
      $SHELL_WRAPPER timeout -k 10 "${HOST_OS_TEST_TIMEOUT}" \
          "$CI_PROJECT_DIR"/ic-os/hostos/tests/hostos-upgrade.sh "$CI_PROJECT_DIR"
