.build-and-test-monpoly-docker: &build-and-test-monpoly-docker |
  
  # build monpoly_pipeline container image
  docker build --build-arg MONPOLY_PIPELINE_GIT_REVISION="${CI_COMMIT_SHA}" -t monpoly_pipeline:"${CI_COMMIT_SHA}" ./policy-monitoring
  
  # run monpoly_pipeline docker container with timeout 360 seconds
  MONPOLY_DID=$(docker run -d -it --rm monpoly_pipeline:"${CI_COMMIT_SHA}" "sleep 360")
  docker exec "${MONPOLY_DID}" python3 -m tests.monpoly_io
  docker exec "${MONPOLY_DID}" python3 -m tests.global_infra_io
  docker exec "${MONPOLY_DID}" python3 -m tests.mfotl_sanity

  # clean the container
  docker rm -f "${MONPOLY_DID}"

deploy-monpoly-docker:
  extends:
    - .ubuntu-nix-docker
    - .rules-monpoly-deploy
  stage: prod-tests
  script:
    - set -euo pipefail
    - TAG=$(date '+%Y-%m-%d-%H%M')
    - *build-and-test-monpoly-docker
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    - docker tag monpoly_pipeline:"${CI_COMMIT_SHA}" dfinity/monpoly_pipeline:"$TAG"
    - docker push dfinity/monpoly_pipeline:"$TAG"
    - docker tag monpoly_pipeline:"${CI_COMMIT_SHA}" dfinity/monpoly_pipeline:latest
    - docker push dfinity/monpoly_pipeline:latest
