no-interrupt:
  extends:
    - .ubuntu-cargo-k8s
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  stage: init
  interruptible: False
  script:
    - echo "This pipeline is not interruptible"

cargo-audit:
  extends:
    - .ubuntu-cargo-k8s
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "cargo-audit"'
  stage: init
  script:
    - cd rs; cargo audit
