[package]
name = "ic-btc-kyt"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[[bin]]
name = "ic-btc-kyt-canister"
path = "src/main.rs"

[dependencies]
bitcoin = { version = "0.28.1", default-features = false, features = ["no-std"] }
candid = { workspace = true }
futures = { workspace = true }
ic-cdk = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
candid_parser = { workspace = true }
ic-state-machine-tests = { path = "../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../test_utilities/load_wasm" }
