[workspace]

[package]
name = "attestee"
description = "Remote attestation TODO."
license = "Apache-2.0"
edition = "2021"

[dependencies]
#candid = "0.10.11"
#ic-agent = "0.39.1"
sev = { version = "6.0.0", features = ["crypto_nossl", "sev"] }
#anyhow = "1.0.93"
#sha2 = "0.11.0-pre.4"
#der = { version = "0.8.0-rc.1", features = ["alloc", "derive", "std"] }
#mockall = "0.13.1"
#tokio = { version = "1.42.0", features = ["macros"] }
#ic-certified-map = "0.4"
#serde_cbor = "0.11"
#attestation = {path = "../attestation"}
#attestation-token = {path = "../attestation_token"}
#thiserror = "1.0.68"
#async-trait = "0.1.83"
reqwest = { version = "0.12.15", features = ["json", "blocking"] }

[[bin]]
name = "renew_attestation_token"

[lib]
name = "attestee"
