[package]
name = "ic-test-utilities-serialization"
version = "0.8.0"
edition = "2021"

[dev-dependencies]
assert_matches = "1"
ic-protobuf = { path = "../../protobuf" }
prost = "0.11"
serde = { version = "1", features = ["derive"] }
serde_cbor = "0.11"
serde_json = "1"
