[package]
name = "ic-test-utilities-serialization"
version = "0.8.0"
edition = "2021"

[dev-dependencies]
assert_matches = "1"
ic-protobuf = { path = "../../protobuf" }
prost = "0.11"
serde = { workspace = true }
serde_cbor = { workspace = true }
serde_json = { workspace = true }
