[package]
name = "ic-crypto-secrets-containers"
version = "0.8.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }

[dev-dependencies]
serde_cbor = { workspace = true }
serde_bytes = { workspace = true }
