[package]
name = "ic-btc-types-internal"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.8.1"
ic-btc-interface = { git = "https://github.com/dfinity/bitcoin-canister", rev = "e4e89f2caedffbe0cfdec6f9d4a77f66dcb9119e" }
ic-protobuf = { path = "../../../protobuf" }
serde = "1.0.132"
serde_bytes = "0.11"
