[package]
name = "ic-btc-types-internal"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
ic-btc-interface = { workspace = true }
ic-error-types = { path = "../../../types/error_types" }
ic-protobuf = { path = "../../../protobuf" }
serde = { workspace = true }
serde_bytes = { workspace = true }
