[package]
name = "subnet-splitting-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
hex = "0.4.2"
ic-base-types = { path = "../../types/base_types/" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-protobuf = { path = "../../protobuf" }
ic-recovery = { path = "../" }
ic-replay = { path = "../../replay" }
ic-state-manager = { path = "../../state_manager" }
ic-registry-routing-table = { path = "../../registry/routing_table" }
ic-types = { path = "../../types/types" }
url = { version = "2.1.1", features = ["serde"] }
serde = { version = "1.0.115", features = ["derive"] }
slog = { version = "2.5.2", features = ["release_max_level_trace"] }
strum = "0.24.1"
strum_macros = "0.24.1"

[dev-dependencies]
ic-test-utilities-tmpdir = { path = "../../test_utilities/tmpdir" }

[[bin]]
name = "subnet-splitting-tool"
path = "src/main.rs"
