[package]
name = "response-payload-test"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[[bin]]
name = "response-payload-test-canister"
path = "src/main.rs"

[dependencies]
candid = { workspace = true }
ic-cdk = "0.17.2"
ic-cdk-macros = "0.17.2"
serde = { workspace = true }
