[package]
name = "ic-crypto-utils-time"
description = "Utils for time source"
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true

[dependencies]
ic-logger = { path = "../../../monitoring/logger" }
ic-interfaces = { path = "../../../interfaces" }
ic-types = { path = "../../../types/types" }
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
