[package]
name = "ic-rosetta-test-utils"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
base64 = { workspace = true }
hex = "0.4.2"
ic-canister-client-sender = { path = "../../canister_client/sender" }
ic-rosetta-api = { path = "../" }
ic-types = { path = "../../types/types" }
icp-ledger = { path = "../icp_ledger" }
log = "0.4.14"
nix = { workspace = true }
rand = "0.8"
serde = { workspace = true }
serde_json = { workspace = true }
slog = { version = "2.5.2", features = ["release_max_level_trace"] }
tempfile = "3.1.0"
reqwest = "0.11.1"
tokio = { workspace = true }
url = "2.1.1"
