[package]
name = "ic-btc-replica-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
candid = { workspace = true }
ic-btc-interface = { workspace = true }
ic-doge-interface = { git = "ssh://git@github.com/dfinity/dogecoin-canister" }
ic-error-types = { path = "../../../packages/ic-error-types" }
ic-protobuf = { path = "../../protobuf" }
serde = { workspace = true }
serde_bytes = { workspace = true }
