[package]
name = "ic-icp-index"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "Index canister for the ICP Ledger"
edition = "2018"

[[bin]]
name = "ic-icp-index"
path = "src/main.rs"
