[package]
name = "ic-identity"
description = "A tool to generate necessary crypto keys for IC admins and users."
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
ic-crypto-ed25519 = { path = "../crypto/ed25519" }
