[package]
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
name = "phantom_newtype"
version.workspace = true

[dependencies]
candid = { workspace = true }
ic-deterministic-heap-bytes = { path = "../../packages/ic-deterministic-heap-bytes" }
num-traits = { workspace = true }
serde = { workspace = true }
slog = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
