[package]
name = "ic-nns-handler-recovery-client"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
candid = { workspace = true }
serde = { workspace = true }
ic-agent.workspace = true
async-trait.workspace = true
ic-nns-handler-recovery-interface.path = "../interface"

[dev-dependencies]
tokio.workspace = true
p256.workspace = true
k256.workspace = true
ed25519-dalek.workspace = true
pocket-ic.path = "../../../../../packages/pocket-ic"
