[package]
name = "ic-https-outcalls-service"
version = "0.1.0"

[dependencies]
prost = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
tonic-build = { workspace = true }
