# certificate-issuer

[sources.certificate_issuer]
type = "journald"
include_units = ["certificate-issuer"]

[transforms.certificate_issuer_normalized]
type = "remap"
inputs = ["certificate_issuer"]
source = """
. = parse_json!(.message)

.service = "certificate-issuer"
.timestamp = to_timestamp!(.timestamp, unit: "nanoseconds")
"""

# certificate-syncer

[sources.certificate_syncer]
type = "journald"
include_units = ["certificate-syncer"]

[transforms.certificate_syncer_normalized]
type = "remap"
inputs = ["certificate_syncer"]
source = """
. = parse_json!(.message)

.service = "certificate-syncer"
.timestamp = to_timestamp!(.timestamp, unit: "nanoseconds")
"""

# ic-boundary

[sources.ic_boundary]
type = "journald"
include_units = ["ic-boundary"]

[transforms.ic_boundary_normalized]
type = "remap"
inputs = ["ic_boundary"]
source = """
. = parse_json!(.message)

.service = "ic-boundary"
.timestamp = to_timestamp!(.timestamp, unit: "nanoseconds")
"""

[transforms.ic_boundary_filtered]
type = "filter"
inputs = ["ic_boundary_normalized"]
condition = """
    !includes([
        \"check\",
        \"http_request_in\",
    ], .action)
"""

[sinks.console]
type = "console"
encoding.codec = "json"
inputs = [
  "certificate_issuer_normalized",
  "certificate_syncer_normalized",
  "ic_boundary_filtered",
]
