[package]
name = "ic-crypto-test-utils-tls"
version = "0.8.0"
edition = "2021"
description = "Test utility for TLS"

[dependencies]
ic-protobuf = { path = "../../../protobuf" }
ic-registry-client-fake = { path = "../../../registry/fake" }
ic-registry-keys = { path = "../../../registry/keys" }
ic-registry-proto-data-provider = { path = "../../../registry/proto_data_provider" }
ic-types = { path = "../../../types/types" }
openssl = "0.10.55"
tokio = { version = "1.32.0", features = ["net"] }
tokio-openssl = "0.6.0"
