[package]
name = "ic-node-rewards-canister"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[[bin]]
name = "node-rewards-canister"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
candid = { workspace = true }
futures = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-management-canister-types = { workspace = true }
ic-metrics-encoder = "1.1.1"
ic-nervous-system-canisters = { path = "../../nervous_system/canisters" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nns-constants = { path = "../../nns/constants" }
ic-node-rewards-canister-api = { path = "./api" }
ic-registry-canister-client = { path = "../../registry/canister-client" }
ic-registry-keys = { path = "../../registry/keys" }
ic-registry-nns-data-provider = { path = "../../registry/nns_data_provider" }
ic-registry-node-provider-rewards = { path = "../../registry/node_provider_rewards" }
ic-stable-structures = { workspace = true }
ic-base-types = { path = "../../types/base_types" }
ic-types = { path = "../../types/types" }
ic-protobuf = { path = "../../protobuf" }
indexmap = { workspace = true }
mockall = { workspace = true }
prost = { workspace = true }
rewards-calculation = { path = "../rewards_calculation" }
serde = { workspace = true }
itertools = { workspace = true }
url = "2.5.4"
ic-agent = { workspace = true }

[dev-dependencies]
candid_parser = { workspace = true }
futures-util = { workspace = true }
ic-state-machine-tests = { path = "../../state_machine_tests" }
ic-nervous-system-agent = { path = "../../nervous_system/agent", features = ["test"] }
ic-nervous-system-integration-tests = { path = "../../nervous_system/integration_tests" }
ic-nns-test-utils = { path = "../../nns/test_utils" }
maplit = "1.0.2"
chrono = "0.4.41"
pocket-ic = { path = "../../../packages/pocket-ic" }
rust_decimal = "1.37.1"
rust_decimal_macros = "1.37.1"
serde_json = { workspace = true }
tabled = "0.20.0"
tokio = { workspace = true }
flate2 = "1.0"
tar = "0.4"
tempfile = "3.3"
ic-registry-transport = { path = "../../registry/transport" }
csv = "1.3.1"
pretty_assertions = { workspace = true }

[features]
test = []
