[package]
name = "fees-and-limits"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-config = { path = "../../config" }
ic-embedders = { path = "../../embedders" }
ic-replicated-state = { path = "../../replicated_state" }
ic-system-api = { path = "../../system_api" }
ic-types = { path = "../../types/types" }
serde = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "fees_and_limits"
path = "src/fees_and_limits.rs"
