[package]
name = "icrc-ledger-agent"
version = "0.1.0"
edition = "2021"
description = "Functions for interacting with DFINITY's implementation of the ICRC-1 fungible token standard."
license = "Apache-2.0"
readme = "README.md"
include = ["src", "Cargo.toml", "CHANGELOG.md", "LICENSE", "README.md"]
repository = "https://github.com/dfinity/ic"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.8.1"
garcon = { version = "0.2", features = ["async"] }
ic-agent = "=0.22.0"
icrc-ledger-types = { path = "../icrc-ledger-types" }
