[package]
name = "ic-xnet-uri-new"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
http = { workspace = true }
ic-types = { path = "../../types/types" }