[package]
name = "ic-drun"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
pocket-ic = { path = "../../packages/pocket-ic" }
ic-execution-environment = { path = "../execution_environment" }
ic-interfaces = { path = "../interfaces" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-management-canister-types = { path = "../types/management_canister_types" }
ic-types = { path = "../types/types" }
clap = { version = "3.2.25", features = ["derive"] }
futures = { workspace = true }
hex = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
wasmparser = "0.115.0"
wat = "1.0.52"

[[bin]]
name = "drun"
path = "src/main.rs"
