[package]
name = "ic-drun"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
candid = { workspace = true }
clap = { version = "3.2.25", features = ["derive"] }
hex = { workspace = true }
pocket-ic = { path = "../../packages/pocket-ic" }
serde = { workspace = true }
tempfile = { workspace = true }
wasmparser = "0.115.0"

[dev-dependencies]
wat = "1.0.52"

[[bin]]
name = "drun"
path = "src/main.rs"
