[package]
name = "ic-test-utilities-crypto"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-crypto-interfaces-sig-verification = { path = "../../crypto/interfaces/sig_verification" }
ic-crypto-internal-types = { path = "../../crypto/internal/crypto_lib/types" }
ic-crypto-temp-crypto = { path = "../../crypto/temp_crypto" }
ic-crypto-test-utils-canister-threshold-sigs = { path = "../../crypto/test_utils/canister_threshold_sigs" }
ic-crypto-test-utils-ni-dkg = { path = "../../crypto/test_utils/ni-dkg" }
ic-interfaces = { path = "../../interfaces" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-registry-client-fake = { path = "../../registry/fake" }
ic-registry-proto-data-provider = { path = "../../registry/proto_data_provider" }
ic-test-utilities-types = { path = ".././types" }
ic-types = { path = "../../types/types" }
ic-types-test-utils = { path = "../../types/types_test_utils" }
rand = { workspace = true }
