[package]
name = "create-nervous-system-upgrade-proposal-texts"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[[bin]]
name = "create-nervous-system-upgrade-proposal-texts"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
candid = { workspace = true }
colored = "2.0.0"
clap = { workspace = true }
futures = { workspace = true }
ic-agent = { workspace = true }
ic-base-types = { path = "../../../types/base_types" }
ic-nervous-system-agent = { path = "../../agent" }
ic-nervous-system-clients = { path = "../../clients" }
ic-nervous-system-common-test-keys = { path = "../../common/test_keys" }
ic-nns-common = { path = "../../../nns/common" }
ic-nns-constants = { path = "../../../nns/constants" }
rgb = "0.8.37"
serde = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
