[package]
name = "ic-nervous-system-humanize"
version = "0.0.1"
edition = "2021"

[dependencies]
humantime = "2.1.0"
ic-nervous-system-proto = { path = "../proto" }
lazy_static = "1.4.0"
regex = "1.3.0"
serde = "1.0.99"

[dev-dependencies]
serde_yaml = "0.8.24"