[package]
name = "ic-validator-ingress-message-test-canister"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
# This MUST be kept in sync with build-info-build in the [build-dependencies] section!
build-info = { version = "0.0.26", default-features = false, features = [] }

candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-types = { path = "../../../types/types" }
ic-validator-ingress-message = { path = ".." }

[build-dependencies]
# This MUST be kept in sync with build-info in the [dependencies] section!
build-info-build = { version="0.0.26", default-features = false, features = [] }

[dev-dependencies]
canister-test = { path = "../../../rust_canisters/canister_test" }
ic-state-machine-tests = { path = "../../../state_machine_tests" }
ic-types = { path = "../../../types/types" }
tokio = { workspace = true }
