[package]
name = "poc"
version = "9.0.1"
license = "Apache-2.0"
description = "PocketIC: A Canister Smart Contract Testing Platform"
repository = "https://github.com/dfinity/ic"
documentation = "https://docs.rs/pocket-ic/latest/pocket_ic/"
readme = "README.md"
categories = ["emulators", "development-tools::testing", "wasm"]
keywords = ["icp", "canister", "testing", "smart-contract", "internet-computer"]
include = [
    "src",
    "Cargo.toml",
    "CHANGELOG.md",
    "README.md",
    "HOWTO.md",
    "LICENSE",
]
authors.workspace = true
edition.workspace = true

[dev-dependencies]
axum = { workspace = true }
ic-agent = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }
tokio = { workspace = true }
axum-server = { workspace = true }
