[package]
name = "icx-proxy"
authors = ["DFINITY Stiftung <sdk@dfinity.org>"]
edition = "2018"
description = "CLI tool to create an HTTP proxy to the Internet Computer."
homepage = "https://docs.rs/icx-proxy"
documentation = "https://docs.rs/icx-proxy"
license = "Apache-2.0"
readme = "README.md"
categories = ["command-line-interface", "web-programming::http-server"]
keywords = ["internet-computer", "agent", "icp", "dfinity", "proxy"]
include = ["src", "Cargo.toml", "../LICENSE", "README.md"]
version.workspace = true

[[bin]]
name = "icx-proxy"
path = "src/main.rs"

[dependencies]
anyhow = "1"
async-trait = "0.1"
axum = "0.6.1"
bytes = { workspace = true }
candid = { workspace = true }
clap = { version = "4", features = ["cargo", "derive"] }
form_urlencoded = "1"
futures = { workspace = true }
http = "0.2.6"
http-body = "0.4"
hyper = { version = "0.14.26", features = ["client", "http2", "http1"] }
hyper-rustls = { version = "0.24.0", features = ["http2"] }
itertools = { workspace = true }
ic-agent = { workspace = true }
ic-utils = { workspace = true, features = ["raw"] }
jemallocator = "0.3"
opentelemetry = { version = "0.20", features = ["metrics"] }
opentelemetry-prometheus = "0.13.0"
prometheus = { workspace = true }
rustls = { version = "0.21", features = ["dangerous_configuration"] }
rustls-native-certs = "0.6.2"
rustls-pemfile = "1"
tokio-util = { workspace = true }
tower = { workspace = true }
tower-http = { version = "0.3", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
tokio = { workspace = true }
ic-response-verification = { workspace = true }
ic-http-certification = { workspace = true }
thiserror = "1.0.40"

[features]
skip_body_verification = []
dev_proxy = []

[dev-dependencies]
tokio-test = "0.4.2"
