[package]
name = "tla-instrumentation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
serde = { workspace = true }
tla-instrumentation-proc-macros = { path = "../tla_instrumentation_proc_macros" }
sha2 = { workspace = true }

[dev-dependencies]
tokio-test = "0.4.4"
local-key = { path = "../local_key" }
