[package]
name = "ic-certified-blockchain-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
hex = "0.4.3"
ic-certified-map = "0.3.1"
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-stable-structures = { workspace = true }
num = "0.4"
num-traits = "0.2.12"
num-derive = "0.3"
prost = "0.11"
serde = { version = "1.0.99", features = [ "derive" ] }
serde_bytes = "0.11"
serde_cbor = "0.11.2"
sha2 = "^0.10.2"
url = "2.1.1"

[profile.release]
debug = false
lto = true
opt-level = 'z'
