[package]
name = "ic-certified-blockchain-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.8.1"
hex = "0.4.3"
ic-certified-map = "0.3.1"
ic-cdk = "0.7"
ic-cdk-macros = "0.6.8"
ic-cdk-timers = "0.1"
ic-stable-structures = "0.5"
num = "0.4"
num-traits = "0.2.12"
num-derive = "0.3"
prost = "0.11"
serde = { version = "1.0.99", features = [ "derive" ] }
serde_bytes = "0.11"
serde_cbor = "0.11.2"
sha2 = "^0.10.2"
url = "2.1.1"

[profile.release]
debug = false
lto = true
opt-level = 'z'
