[package]
name = "dfn_http"
version = "0.8.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
serde = { workspace = true }
dfn_candid = { path = "../dfn_candid" }
dfn_core = { path = "../dfn_core" }
serde_bytes = { workspace = true }

[[bin]]
name = "http_wasm"
path = "test/wasm.rs"
