[package]
name = "xrc-mock"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
candid = { workspace = true }
ic-cdk = "0.17.2"
ic-cdk-macros = "0.17.2"
ic-xrc-types = "1.1.0"
serde = { workspace = true }
