[package]
name = "libsigsegv"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
lazy_static = "*"
libc = "*"
libsigsegv-sys = { path = "../libsigsegv-sys" }
slog = "*"
slog-scope = "*"
