[package]
name = "launch-single-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tests = { path = "../../tests"}
ic-prep = { path = "../../prep"}
ic-registry-subnet-type = { path = "../../registry/subnet_type"}
ic-types = { path = "../../types/types" }

clap = { version = "3.1.6", features = ["derive"] }
reqwest = { version = "0.11.1", features = ["blocking", "multipart", "stream"] }
serde = { workspace = true }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
slog = { version = "2.5.2", features = ["release_max_level_trace"] }
tempfile = "3.1.0"
url = "2.1.1"
