[package]
name = "ic-icrc1-test-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
candid = { workspace = true }
ic-icrc1 = { path = ".." }
ic-ledger-core = { path = "../../ledger_core" }
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
num-traits = "0.2.15"
proptest = "1.0"
rand = "0.8"
serde_bytes = { workspace = true }
ic-ledger-canister-core = { path = "../../ledger_canister_core" }