[package]
name = "ic-icrc1-test-utils"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
candid = "0.8.1"
ic-icrc1 = { path = ".." }
ic-ledger-core = { path = "../../ledger_core" }
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
proptest = "1.0"
rand = "0.8"
serde_bytes = "0.11"