[package]
name = "ic-registry-keys"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
candid = { workspace = true }
ic-base-types = { path = "../../types/base_types" }
ic-management-canister-types = { workspace = true }
ic-types = { path = "../../types/types" }
serde = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
