[package]
name = "ic-registry-keys"
version = "0.8.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
ic-base-types = { path = "../../types/base_types" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-types = { path = "../../types/types" }
serde = { workspace = true }

[dev-dependencies]
rand = "0.8"
