[package]
name = "ic-btc-adapter-test-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
bitcoin = { version = "0.28.1", features = ["default", "use-serde", "rand"] }
hex = "0.4.2"
rand = "0.8.3"
