[package]
name = "pocket-ic-server"
version = "0.2.0"
edition = "2021"

[dependencies]
axum = { version = "^0.6.1", features = ["headers"] }
candid = { workspace = true }
rand = "^0.8.5"
itertools = "0.11"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "^1.0"
pocket-ic = { path = "../../packages/pocket-ic" }
ic-state-machine-tests = { path = "../state_machine_tests" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-interfaces-state-manager = { path = "../interfaces/state_manager" }
ic-config = { path = "../config" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-crypto = { path = "../crypto" }
ic-types = { path = "../types/types" }
ic-crypto-iccsa = { path = "../crypto/iccsa" }
ic-cdk = { workspace = true }
ic-crypto-sha2 = { path = "../crypto/sha2" }
ic-utils = { path = "../utils" }
hex = "0.4.2"
ic-crypto-utils-threshold-sig-der = { path = "../crypto/utils/threshold_sig_der" }
clap = { version = "3.1.6", features = ["derive"] }
sha2 = "0.9.3"
time = "^0.3.20"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "^0.2.2"
tower-http = { version = "^0.4.4", features = [
    "trace",
    "request-id",
    "util",
    "timeout",
] }
tempfile = "*"
base64 = { workspace = true }
wat = "1.0.52"
flate2 = "1.0.27"

[dev-dependencies]
reqwest = "*"
