[package]
name = "ic-crypto-internal-types"
version = "0.8.0"
edition = "2021"

[dependencies]
arrayvec = "0.5.1"
hex = "0.4.2"
ic-protobuf = { path = "../../../../protobuf" }
phantom_newtype = { path = "../../../../phantom_newtype" }
serde = { workspace = true }
serde_cbor = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = "1.0"
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }

[dev-dependencies]
