[package]
name = "ic_sev"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
der = { workspace = true }
mockall = { workspace = true }
reqwest = { workspace = true }
sev = { workspace = true }
tempfile = { workspace = true }
base64 = { workspace = true }
#hmac = { path = "../../crypto/internal/crypto_lib/hmac"}
clap = { version = "4.5.41", features = ["derive"] }

[dev-dependencies]
pem = { workspace = true }
rcgen = { workspace = true }
