[package]
name = "proxy_canister"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-cdk = "0.5.5"
candid = "0.7.12"
ic-cdk-macros = "0.5.0"
serde = "1.0.136"
ic-ic00-types = { path = "../../types/ic00_types" }
ic-base-types = { path = "../../types/base_types" }
ic-types = { path = "../../types/types" }
wasm-bindgen = "0.2"
dfn_core = { path = "../dfn_core" }
dfn_candid = { path = "../dfn_candid" }

[[bin]]
name = "proxy_canister"
path = "src/main.rs"

