[package]
name = "proxy_canister"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-management-canister-types = { path = "../../types/management_canister_types" }
serde = { workspace = true }

[[bin]]
name = "proxy_canister"
path = "src/main.rs"
