[package]
name = "test_registry_builder"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
prost = { workspace = true }
ic-protobuf = { path = "../../../protobuf" }
ic-registry-keys = { path = "../../../registry/keys" }
ic-registry-transport = { path = "../../transport" }
ic-types = { path = "../../types/types" }
ic-nns-test-utils = { path = "../../../nns/test_utils" }
ic-base-types = { path = "../../../types/base_types/" }
ic-base-types = { path = "../../../types/base_types/" }
ic-crypto-node-key-validation = { path = "../../../crypto/node_key_validation" }



