[package]
name = "ic-consensus-mocks"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-artifact-pool = { path = "../../artifact_pool" }
ic-config = { path = "../../config" }
ic-consensus-utils = { path = "../utils" }
ic-interfaces = { path = "../../interfaces" }
ic-interfaces-state-manager = { path = "../../interfaces/state_manager" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-client-fake = { path = "../../registry/fake" }
ic-registry-keys = { path = "../../registry/keys" }
ic-registry-proto-data-provider = { path = "../../registry/proto_data_provider" }
ic-test-artifact-pool = { path = "../../test_utilities/artifact_pool" }
ic-test-utilities = { path = "../../test_utilities" }
ic-test-utilities-registry = { path = "../../test_utilities/registry" }
ic-types = { path = "../../types/types" }
mockall = "0.7.2"
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }