[package]
name = "pocket-ic-backend" 
version = "0.0.1"
edition = "2021"

[dependencies]
candid = "^0.9"
clap = "^4.0"
axum = "^0.6"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }

