[package]
name = "ic-ckdoge-minter"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[[bin]]
name = "ic-doge-minter"
path = "src/main.rs"

[dependencies]
candid = { workspace = true }
ic-ckbtc-minter = { path = "../../../bitcoin/ckbtc/minter" }
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
serde = { workspace = true }
