[package]
name = "ic-onchain-observability-server"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-async-utils = { path = "../../../async_utils" }
ic-metrics = { path = "../../../monitoring/metrics" }
ic-onchain-observability-service = { path = "../service" }
prometheus = { version = "0.12.0", features = [ "process" ] }
tokio = "1.15.0"
tonic = "0.8.3"