[package]
name = "discower_bowndary"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.73"
ic-agent = "0.27.0"
prost = "0.11.9"
tokio = "1.32.0"
url = "2.4.0"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
futures-util = "0.3.28"
reqwest = "0.11.18"
thiserror = "1.0.50"
ic-registry-client = { path = "../../registry/client" }
ic-registry-nns-data-provider-wrappers = { path = "../../registry/nns_data_provider_wrappers" }

[lib]
name = "discower_bowndary"
