[package]
name = "inject-files"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
partition_tools = { path = "../partition_tools" }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio = { workspace = true }
