[package]
name = "call-tree-test"
version = "0.8.0"
edition = "2021"

[[bin]]
name = "call-tree-test-canister"
path = "src/main.rs"

[dependencies]
dfn_core = { path = "../dfn_core" }
dfn_json = { path = "../dfn_json" }
dfn_macro = { path = "../dfn_macro" }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
