[package]
name = "ic-ledger-suite-orchestrator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ic-leger-suite-orchestrator"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.73"
candid = { workspace = true }
ciborium = { workspace = true }
hex = "0.4"
ic-canister-log = "0.2.0"
ic-base-types = { path = "../../types/base_types" }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-crypto-sha2 = { path = "../../crypto/sha2" }
ic-ethereum-types = { path = "../types"}
ic-ic00-types = { path = "../../types/ic00_types" }
icrc-ledger-types = { path = "../../../packages/icrc-ledger-types" }
ic-icrc1-index-ng = { path = "../../rosetta-api/icrc1/index-ng" }
ic-icrc1-ledger = { path = "../../rosetta-api/icrc1/ledger" }
ic-stable-structures = { workspace = true }
num-traits = "0.2.14"
serde = { workspace = true }
serde_json = { workspace = true }
serde_bytes = { workspace = true }

[dev-dependencies]
proptest = "1.0"
candid_parser = { workspace = true }
ic-state-machine-tests = { path = "../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../test_utilities/load_wasm" }
mockall = { workspace = true }
paste = "1.0.12"
tokio = { workspace = true }
