[package]
name = "ic-utils-lru-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-types = { path = "../../types/types" }
lru = { version = "0.7.8", default-features = false }
