[package]
name = "ic-test-utilities-idkg"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-artifact-pool = { path = "../../artifact_pool" }
ic-config = { path = "../../config" }
ic-consensus = { path = "../../consensus", features = ["malicious_code"] }
ic-consensus-mocks = { path = "../../consensus/mocks" }
ic-consensus-utils = { path = "../../consensus/utils" }
ic-crypto-temp-crypto = { path = "../../crypto/temp_crypto" }
ic-crypto-test-utils-canister-threshold-sigs = { path = "../../crypto/test_utils/canister_threshold_sigs" }
ic-crypto-test-utils-reproducible-rng = { path = "../../crypto/test_utils/reproducible_rng" }
ic-crypto-tree-hash = { path = "../../crypto/tree_hash" }
ic-interfaces = { path = "../../interfaces" }
ic-interfaces-state-manager = { path = "../../interfaces/state_manager" }
ic-logger = { path = "../../monitoring/logger" }
ic-management-canister-types-private = { path = "../../types/management_canister_types" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-replicated-state = { path = "../../replicated_state" }
ic-state-manager = { path = "../../state_manager" }
ic-test-artifact-pool = { path = "../../test_utilities/artifact_pool" }
ic-test-utilities = { path = "../../test_utilities" }
ic-test-utilities-consensus = { path = "../../test_utilities/consensus" }
ic-test-utilities-state = { path = "../../test_utilities/state" }
ic-test-utilities-types = { path = "../../test_utilities/types" }
ic-types = { path = "../../types/types" }
ic-types-test-utils = { path = "../../types/types_test_utils" }
rand = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

[features]
default = []
malicious_code = []
proptest = []
