[package]
name = "ic-tvl-sm-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.8.1"
ic-tvl-canister = { path = "../" }
ic-base-types = { path = "../../../types/base_types" }
ic-nns-governance = { path = "../../../nns/governance" }
ic-nns-test-utils = { path = "../../../nns/test_utils" }
ic-state-machine-tests = { path = "../../../state_machine_tests" }
num-traits = "0.2.14"
proptest = "1.0"
cddl = "0.9.0-beta.1"
hex = "0.4.2"

