[package]
name = "vsock_guest"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_os = "linux")'.dependencies]
clap = { workspace = true }
vsock_lib = { path = "../vsock_lib" }
vsock_lib = { path = "../vsock_lib" }
