[package]
name = "ic-nervous-system-long-message"
version = "0.0.1"
edition = "2021"

[dependencies]

[dev-dependencies]
candid = { workspace = true }
ic-base-types = { path = "../../types/base_types" }
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ic-state-machine-tests = { path = "../../state_machine_tests" }
ic-nns-test-utils = { path = "../../nns/test_utils" }
canister-test = { path = "../../rust_canisters/canister_test" }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
