[package]
name = "ic-backup"
version = "0.8.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
ic-types = { path = "../types/types" }
ic-recovery = { path = "../recovery" }
rand = "0.8"
serde_json = "1.0.54"
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
tokio = { version = "1.15.0", features = ["full"] }

[[bin]]
name = "ic-backup"
path = "src/main.rs"