[package]
name = "ic-ledger-canister-blocks-synchronizer-test-utils"
version = "0.1.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
ed25519-dalek = "1.0.1"
ic-canister-client = { path = "../../../canister_client" }
ic-cdk = { version = "0.5.1" }
ic-ledger-canister-blocks-synchronizer = { path = "../" }
ic-ledger-core = { path = "../../ledger_core" }
ic-types = { path = "../../../types/types" }
ledger-canister = {path = "../../ledger_canister"}
log = "0.4.14"
log4rs = "1.1.1"
rand = "0.7"
rand_distr = "0.3.0"
tempfile = "3.1.0"
tokio = { version = "1.15.0", features = ["full"] }
