[package]
name = "ic-quic-transport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
bytes = { workspace = true }
either = "1.6.0"
futures = { workspace = true }
ic-async-utils = { path = "../../async_utils" }
ic-crypto-tls-interfaces = { path = "../../crypto/tls_interfaces" }
ic-crypto-utils-tls = { path = "../../crypto/utils/tls" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-base-types = { path = "../../types/base_types" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-protobuf = { path = "../../protobuf" }
phantom_newtype = { path = "../../phantom_newtype" }
prometheus = { workspace = true }
prost = { workspace = true }
quinn = { workspace = true }
reed-solomon-erasure = "6.0.0"
reed-solomon-simd = "2.2.2"
raptor-code = "1.0.6"
rustls = { version = "0.21.12", features = ["dangerous_configuration"] }
slog = { workspace = true }
socket2 = { workspace = true }
tokio = { workspace = true }
tokio-metrics = { workspace = true }
tokio-util = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
ic-p2p-test-utils = { path = "../test_utils" }
ic-test-utilities-logger = { path = "../../test_utilities/logger" }
ic-types-test-utils = { path = "../../types/types_test_utils" }
turmoil = { workspace = true }
