[package]
name = "ic-tvl-canister"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ic-tvl-canister"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.59"
candid = "0.8.4"
walkdir = "2.3.2"
ciborium = { workspace = true }
futures = "0.3.25"
ic0 = "0.18.9"
ic-base-types = { path = "../../types/base_types" }
ic-nns-governance = { path = "../../nns/governance" }
ic-canisters-http-types = { path = "../../rust_canisters/http_types" }
ic-cdk = "0.7.0"
ic-cdk-timers = "0.1.2"
ic-cdk-macros = "0.6.8"
ic-metrics-encoder = "1"
ic-stable-structures = "0.5.0"
num-traits = "0.2.15"
serde = "1.0"
serde_bytes = "0.11"

[dev-dependencies]
assert_matches = "1.3.0"
ic-nns-test-utils = { path = "../../nns/test_utils" }
ic-state-machine-tests = { path = "../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../test_utilities/load_wasm" }
rand = "0.8.3"
xrc-mock = { path = "xrc_mock" }
