[package]
name = "ic-ckbtc-kyt"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
askama = "0.11"
candid = { workspace = true }
ciborium = { workspace = true }
hex = "0.4.3"
ic-canisters-http-types = { path = "../../../rust_canisters/http_types" }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-metrics-encoder = "1.1"
ic-stable-structures = { workspace = true }
num-traits = "0.2.14"
serde = { workspace = true }
serde_json = { workspace = true }
time = { version = "0.3.20", features = ["formatting"] }

[dev-dependencies]
assert_matches = "1.5.0"
ic-state-machine-tests = { path = "../../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../../test_utilities/load_wasm" }
