[package]
name = "ic-ckbtc-kyt"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.11"
candid = "0.8.1"
ciborium = { git = "https://github.com/enarx/ciborium", rev = "7d8f6e499db51fe52f5d3c2ce1d0e0be61c7eaa2" }
hex = "0.4.3"
ic-canisters-http-types = { path = "../../../rust_canisters/http_types" }
ic-cdk = "0.7.0"
ic-cdk-macros = "0.6.0"
ic-metrics-encoder = "1.1"
ic-stable-structures = "0.5.0"
num-traits = "0.2.14"
serde = "1.0.136"
serde_json = "1.0"
time = { version = "0.3.20", features = ["formatting"] }

[dev-dependencies]
assert_matches = "1.5.0"
ic-state-machine-tests = { path = "../../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../../test_utilities/load_wasm" }
