[package]
name = "ic-async-utils"
version = "0.8.0"
edition = "2021"

[dependencies]
async-stream = "0.3.4"
byte-unit = "4.0.14"
derive_more = "0.99.17"
futures = { workspace = true }
futures-util = "0.3.13"
hyper = { version = "0.14.16", features = ["full"] }
ic-types = { path = "../types/types" }
prometheus = { version = "0.12.0", features = ["process"] }
slog = "2.5.2"
tokio = { version = "1.32.0", features = ["full"] }
tonic = { workspace = true }
tower = { workspace = true }

[dev-dependencies]
bytes = "1.5.0"
rand = "0.8.3"
