[package]
name = "ic-crypto-internal-logmon"
description = "Logging and monitoring for crypto"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
convert_case = "0.6.0"
ic-metrics = { path = "../../../monitoring/metrics" }
prometheus = { workspace = true }
strum = "0.23.0"
strum_macros = "0.23.0"
