[package]
name = "fast-digest"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = { workspace = true }
nix = { version = "0.29.0", features = ["fs"] }
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
anyhow = {workspace = true}
tempfile = "3.15.0"
rand = "0.9.0-beta.3"
