[package]
name = "ic-starter-tests"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
anyhow = { workspace = true }
ic-agent = { workspace = true }
reqwest = { version = "0.11.22", default-features = false, features = [
    "blocking",
    "json",
    "multipart",
    "rustls-tls",
    "rustls-tls-webpki-roots",
    "stream",
] }
tempfile = "3.3.0"
tokio = { workspace = true }
