[package]
name = "ic-starter-tests"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
anyhow = "1.0.58"
ic-agent = { workspace = true }
reqwest = "0.11.13"
tempfile = "3.3.0"
tokio = "1.20.1"
