[package]
name = "ic-starter-tests"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "Build Once. Integrate Your Blockchain Everywhere. "
edition = "2021"

[dependencies]
anyhow = "1.0.58"
ic-agent = "0.22.0"
garcon = "0.2.3"
reqwest = "0.11.13"
tempfile = "3.3.0"
tokio = "1.20.1"