[package]
name = "ic-test-utilities-in-memory-logger"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-config = { path = "../../config" }
ic-logger = { path = "../../monitoring/logger" }
ic-protobuf = { path = "../../protobuf" }
serde_json = { workspace = true }
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
slog-async = { version = "2.5", features = ["nested-values"] }
parking_lot = "0.12.1"
