[package]
name = "ic-btc-validation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = { workspace = true }
primitive-types = "0.13.1"

[dev-dependencies]
csv = "1.1"
