[package]
name = "ic-btc-validation"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = { workspace = true }
hex = { workspace = true }
primitive-types = "0.12"

[dev-dependencies]
csv = "1.1"
proptest = "0.9.4"
rstest = { workspace = true }
