[package]
name = "ic-btc-validation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.32.4"
primitive-types = "0.12"

[dev-dependencies]
csv = "1.1"
proptest = "0.9.4"
