[package]
name = "ic-btc-adapter-client"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-adapter-metrics = { path = "../../monitoring/adapter_metrics" }
ic-async-utils = { path = "../../async_utils" }
ic-btc-service = { path = "../service" }
ic-btc-types-internal = { path = "../types/internal" }
ic-config = { path = "../../config" }
ic-interfaces-adapter-client = { path = "../../interfaces/adapter_client" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
prometheus = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
slog = { version = "2.5.2", features = [
    "nested-values",
    "release_max_level_debug",
] }
tokio = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
