[package]
name = "certificate_orchestrator_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
addr = { version = "0.15.6", default-features = false, features = ["idna"] }
candid = { workspace = true }
ic-stable-structures = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
thiserror = "1.0.37"
