[package]
name = "anonymization-interface"
version = "0.1.0"

[dependencies]
candid = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_bytes = { workspace = true }
serde_bytes = { workspace = true }
