[package]
name = "guestos_tool"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "guestos_tool"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
config = { path = "../../config" }
config_types = { path = "../../config_types" }
indoc = "1.0.9"
itertools = { workspace = true }
network = { path = "../../network" }
regex = { workspace = true }
utils = { path = "../../utils" }
ic_sev = { path = "../../sev" }
nix = { version = "0.30.1", features = ["fs"] }
tempfile = "3.20.0"
rand = "0.8.5"
libcryptsetup-rs = "0.13.1"
grub = { path = "../../grub" }
