[package]
name = "ic-canister-serve"
version = "0.1.0"
edition = "2021"

[dependencies]
by_address = "1.1.0"
ic-canister-log = { path = "../canister_log", version = "0.1.0" }
ic-cdk = "0.7.4"
ic-metrics-encoder = "1.1.0"
maplit = "1.0.2"
priority-queue = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.40"