[package]
name = "setupos_tool"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "setupos_tool"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
config_tool = { path = "../../config_tool" }
network = { path = "../../network" }
utils = { path = "../../utils" }
