[package]
name = "ic-http-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
flate2 = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
hyper-util = { workspace = true }
ic-crypto-sha2 = { path = "../crypto/sha2" }
ic-logger = { path = "../monitoring/logger" }
local-ip-address = { workspace = true }
reqwest = { workspace = true }
slog = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true }
tower-service = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
ic-test-utilities-in-memory-logger = { path = "../test_utilities/in_memory_logger" }
mockito = { workspace = true }
tempfile = { workspace = true }
