[package]
name = "vsock_lib"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_os = "linux")'.dependencies]
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0"
libusb = "0.3"
tempfile = "3.1"
vsock = "0.3"
reqwest = { version = "0.11.1", features = ["blocking"] }
regex = "^1.3"
sha2 = "0.10"

[lib]
name = "vsock_lib"