[package]
name = "ic-crypto-tree-hash-fuzz"
version = "0.8.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = "1.3.0"
libfuzzer-sys = "0.4"
rand = "0.8"
ic-crypto-test-utils-reproducible-rng = { path = "../../test_utils/reproducible_rng" }
ic-crypto-tree-hash = { path = ".." }
ic-crypto-tree-hash-fuzz-check-witness-equality-utils = { path = "check_witness_equality_utils" }
ic-protobuf = { path = "../../../protobuf" }

# Prevent this from interfering with workspaces
[workspace]
members = [".", "check_witness_equality_utils"]

[[bin]]
name = "check_witness_equality"
path = "fuzz_targets/check_witness_equality.rs"
test = false
doc = false
