[package]
name = "ic-validator-ingress-message"
version = "0.8.0"
edition = "2021"
description = "Standalone library to validate ingress messages"

[dependencies]
base64 = "0.13.0"
hex = "0.4.2"
ic-crypto = { path = "../../crypto" }
ic-crypto-temp-crypto = { path = "../../crypto/temp_crypto" }
ic-crypto-utils-threshold-sig-der = { path = "../../crypto/utils/threshold_sig_der" }
ic-interfaces = { path = "../../interfaces" }
ic-logger = { path = "../../monitoring/logger" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-client-fake = { path = "../../registry/fake" }
ic-registry-proto-data-provider = { path = "../../registry/proto_data_provider" }
ic-registry-keys = { path = "../../registry/keys" }
ic-types = { path = "../../types/types" }
ic-validator = { path = "../../validator" }

[dev-dependencies]
assert_matches = "1.5.0"
ic-canister-client-sender = { path = "../../canister_client/sender" }
ic-certification-test-utils = { path = "../../certification/test-utils" }
ic-constants = { path = "../../constants" }
ic-crypto-test-utils-reproducible-rng = { path = "../../crypto/test_utils/reproducible_rng" }
ic-crypto-tree-hash = { path = "../../crypto/tree_hash" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
ic-validator-http-request-test-utils = { path = "../http_request_test_utils" }
rand = "0.8"
strum = "0.23.0"
