[package]
name = "ic-error-types"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-utils = { path = "../../utils" }
serde = { version = "1.0.99", features = ["derive"] }
strum = { workspace = true }
strum_macros = { workspace = true }
