[package]
name = "ic-logger"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
chrono = "0.4.19"
ic-config = { path = "../../config" }
ic-context-logger = { path = "../context_logger" }
ic-protobuf = { path = "../../protobuf" }
serde = { workspace = true }
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-json = { version = "2.3", features = ["nested-values"] }
slog-scope = "4.1.2"
slog-term = "2.6.0"
