file_share_url: 10.10.101.254
file_share_dir: /srv/images
file_share_image_filename: setupos.bmd.img
file_share_username: dfnadmin
inject_image_ipv6_prefix: 2a00:fb01:400:200::/64
inject_image_ipv6_gateway: 2a00:fb01:400:200::1/64
