[package]
name = "ic-crypto-tree-hash"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-crypto-internal-types = { path = "../internal/crypto_lib/types" }
ic-crypto-sha = { path = "../sha" }
ic-protobuf = { path = "../../protobuf" }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"

[dev-dependencies]
assert_matches = "1.5.0"
ic-crypto-test-utils-reproducible-rng = { path = "../test_utils/reproducible_rng" }
maplit = "1.0.2"
proptest = "1.0"
prost = "0.11.0"
rand = "0.8.4"
serde_cbor = "0.11.1"
