name: Governance Team Pull Request Template

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          retries: 3
          script: |
            const nnsTeamMembers = await github.rest.teams.listMembersInOrg({
              org: "dfinity",
              team_slug: "nns-team",
            });
