name: Governance Team Pull Request Template

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - master

jobs:
  # TODO: Change this name to "main".
  template:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PR_AUTOMATION_BOT_PUBLIC_APP_ID }}
          private-key: ${{ secrets.PR_AUTOMATION_BOT_PUBLIC_PRIVATE_KEY }}

      - uses: actions/github-script@v7
        id: main
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          result-encoding: string
          retries: 3
          script: |
            const nnsTeamMembers = await github.rest.teams.listMembersInOrg({
              org: "dfinity",
              team_slug: "nns-team",
            });
