name: Remind Governance Team to Update unreleased_changelog.md.

on:
  pull_request:
    types:
      - opened
      # DO NOT MERGE
      - synchronize

jobs:
  mainJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: mainStep
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retries: 3
          script: |
            // Although this does not DEFINITELY indicated that nns-team MUST
            // approve the PR, it strongly indicates that nns-team must approve.
            const nnsTeamReviewRequested = context
              .payload
              .pull_request
              .requested_teams
              .some(team => team.name == 'nns-team')
            console.log("nnsTeamReviewRequested = " + nnsTeamReviewRequested);
            if (!nnsTeamReviewRequested) {
              return;
            }

            // TODO: Figure out how to post in such a way that there is a "Resolve" button nearby.
            const pullRequestNumber = context.payload.number;
            await github.rest.pulls.createReview({
              owner: "dfinity",
              repo: "ic",
              pull_number: pullRequestNumber,
              body: (
                "Did you remember to update unreleased_changes.md? If so, please, " +
                "explicitly acknowledge this reminder by giving it a thumbs up reaction. " +
                "To unblock the PR, dismiss the code review by going to the bottom " +
                "of the pull request page, and use \"Done.\" as the reason."
              ),
              event: "REQUEST_CHANGES",
            });
