name: Remind Governance Team to Update unreleased_changelog.md.

on:
  pull_request:
    types:
      - opened
      # DO NOT MERGE
      - synchronize

jobs:
  mainJob:
    runs-on: ubuntu-latest
    steps:
      - name: Is the Author in nns-team?
        uses: actions/github-script@v6
        id: isAuthorInNnsTeam
        with:
          github-token: ${{ secrets.CLA_BOT_PRIVATE_KEY }}
          retries: 3
          script: |
            /* DO NOT MERGE
            const pullRequestNumber = context.payload.number;
            console.log("Calling listMembersInOrg...")
            const nnsTeamMembers = await await github.rest.teams.listMembersInOrg({
              org: "dfinity",
              team_slug: "nns-team",
            });
            console.log("nnsTeamMemebrs = " + JSON.stringify(nnsTeamMembers));

            const isInNnsTeam = nnsTeamMembers.data.some(member => member.login == context.actor);
            */
            const isInNnsTeam = true;
            console.log("Is actor in nns-team? " + isInNNsTeam);
            return isInNnsTeam;

      - name: Remind the Author to Update unreleased_changes.md.
        uses: actions/github-script@v6
        if: steps.isAuthorInNnsTeam.outputs.isInNnsTeam == 'true'
        id: remindAuthorToUpdateUnreleasedChangelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retries: 3
          script: |
            // TODO: Figure out how to post in such a way that there is a "Resolve" button nearby.
            await github.rest.pulls.createReview({
              owner: "dfinity",
              repo: "ic",
              pull_number: pullRequestNumber,
              body: (
                "Did you remember to update unreleased_changes.md? If so, please, " +
                "explicitly acknowledge this reminder by giving it a thumbs up reaction. " +
                "To unblock the PR, dismiss the code review by going to the bottom " +
                "of the pull request page, and use \"Done.\" as the reason."
              ),
              event: "REQUEST_CHANGES",
            });
