name: Governance Team Pull Request Template

on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  # TODO: Change this name to "main".
  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: isAuthorInNnsTeam
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          result-encoding: string
          retries: 3
          script: |
            const nnsTeamMembers = await github.rest.teams.listMembersInOrg({
              "dfinity",
              "nns-team",
            });
            console.log("nnsTeamMemebrs = " + nnsTeamMembers);

            const isInNnsTeam = nnsTeamMembers.includes(context.actor);
            if (isInNnsTeam) {
              const pullRequestId = context.pullRequest.id;
              const template = 'Your custom template here';
              await github.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullRequestId,
                body: template,
              });
            }
