name: Governance Team Pull Request Template

on:
  pull_request:
    types:
      - opened
      # DO NOT MERGE
      - synchronize

jobs:
  mainJob:
    runs-on: ubuntu-latest
    steps:
      - name: Main Step
        uses: actions/github-script@v6
        id: main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          retries: 3
          script: |
            console.log("BEGIN SCRIPT"); // DO NOT MERGE

            const oldBody = context.payload.pull_request.body;
            var newBody = oldBody ? [oldBody] : [];

            newBody = newBody.concat([
              "# Added by GitHub Actions",
              "(Or workflows, or whatever TF they are called...)",
            ]);

            newBody = newBody.join("\n\n");
            console.log("newBody = " + JSON.stringify(newBody));

            const pullRequestNumber = context.payload.number;
            console.log("Setting the body of pull request number " + pullRequestNumber + "...");
            await github.rest.pulls.update({
              owner: "dfinity",
              repo: "ic",
              pull_number: pullRequestNumber,
              body: newBody,
            });
