name: Governance Team Pull Request Template

on:
  pull_request:
    types:
      - opened
      - reopened

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PR_AUTOMATION_BOT_PUBLIC_APP_ID }}
          private-key: ${{ secrets.PR_AUTOMATION_BOT_PUBLIC_PRIVATE_KEY }}

      - name: Main Step
        uses: actions/github-script@v6
        id: main
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          result-encoding: string
          retries: 3
          script: |
            console.log("context:\n" + JSON.stringify(context, null, 2) + "\n\n");

            const newBody = context.payload.body + "\n\n# Additional Stuff";
            console.log("newBody = " + newBody);

            const nnsTeamMembers = await github.rest.teams.listMembersInOrg({
              org: "dfinity",
              team_slug: "nns-team",
            });
            console.log("nnsTeamMemebrs = " + nnsTeamMembers);

            const isInNnsTeam = nnsTeamMembers.data.some(member => member.login == context.actor);
            console.log("Is actor in nns-team? " + isInNNsTeam);
            if (!isInNnsTeam) {
              return;
            }

            const pullRequestNumber = context.payload.number;
            await github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequestNumber,
              body: newBody,
            });
