name: Governance Team Pull Request Template

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - master

jobs:
  # TODO: Change this name to "main".
  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: isAuthorInNnsTeam
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          retries: 3
          script: |
            const nnsTeamMembers = await github.rest.teams.listMembersInOrg({
              "dfinity",
              "nns-team",
            });
