name: Main CI

on:
  # Todo: re-enable once github runner resources have been set
  # push:
  merge_group:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

env:
  CI_COMMIT_SHA: ${{ github.sha }}
  CI_COMMIT_REF_PROTECTED: ${{ github.ref_protected }}
  CI_JOB_NAME: ${{ github.job }}
  CI_JOB_ID: ${{ github.job }} # github does not expose this variable https://github.com/orgs/community/discussions/8945
  CI_JOB_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  ROOT_PIPELINE_ID: ${{ github.run_id }}

jobs:
  bazel-test-all:
    name: Bazel-Test-All
    runs-on:
      group: IC
      labels: bazel-runner
    timeout-minutes: 80
    container:
      image: dfinity/ic-build:f46892f10dba6d7839a6e07e30787217a3c06180843472129ceb61534ab1fc9d
    if: ${{ vars.RUN_CI == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Bazel Test All
        id: bazel-test-all
        run: ${GITHUB_WORKSPACE}/gitlab-ci/src/bazel-ci/main.sh
        env:
          BAZEL_COMMAND: "test"
          BAZEL_TARGETS: "//... --deleted_packages=gitlab-ci"
          BAZEL_CI_CONFIG: "--config=ci"
          BAZEL_EXTRA_ARGS: "--keep_going --verbose_failures"
          BAZEL_STARTUP_ARGS: "--output_base=/var/tmp/bazel-output/"
          RUSTFLAGS: "--remap-path-prefix=${CI_PROJECT_DIR}=/ic"
          AWS_SHARED_CREDENTIALS_CONTENT: ${{ secrets.AWS_SHARED_CREDENTIALS_FILE }}
      - name: After script
        run: |
          gzip bazel-build-log*.json
      - name: Upload Bazel artifacts
        uses: actions/upload-artifact@v3
        if: success() || failure() # don't run if CI job is cancelled
        with:
          name: bazel-artifacts
          retention-days: 2
          path: |
            bazel-build-log*.json*
            bazel-bep.pb
            bazel-testlogs/**/test.xml
