name: Main CI

on:
  push:
  merge_group:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Test-All
    runs-on: ubuntu-latest
    if: ${{ vars.RUN_CI == 'true' }}
    steps:
      - name: Test 1
        id: test_1
        run: echo "Success"
