name: PocketIC macOS Intel
on:
  pull_request:
    paths:
      - .github/workflows/pocket-ic-tests-macos-intel.yml
      - packages/pocket-ic/**
      - rs/pocket_ic_server/**
  schedule:
    - cron: "0 1 * * *"

# runs for the same workflow are cancelled on PRs but not on master
# explanation: on push to master head_ref is not set, so we want it to fall back to run_id so it is not cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pocket-ic-tests-on-macos-intel:
    name: PocketIC Tests on macOS Intel
    runs-on:
      labels: macOS
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 256 || 0 }}
      - name: Set PATH
        run: |
          ls -l /usr/local/opt/llvm/bin/clang
          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "$HOME/.cargo/bin:" >> $GITHUB_PATH
          # use llvm-clang instead of apple's
          echo "CC=/usr/local/opt/llvm/bin/clang" >> "$GITHUB_ENV"
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "PATH=\"$HOME/.cargo/bin:$PATH\"" >> $GITHUB_ENV
      - name: Infer macos intel build command
        id: cfg
        run: |
          echo build-command='build --config=ci --config=macos_ci --test_tag_filters=test_macos' >> "$GITHUB_OUTPUT"
      - name: Run Bazel Checks on Darwin x86-64
        id: bazel-test-darwin-x86-64
        uses: ./.github/actions/bazel-test-all/
        with:
          BAZEL_COMMAND: ${{ steps.cfg.outputs.build-command }}
          BAZEL_TARGETS: //rs/pocket_ic_server:pocket-ic-server
          CLOUD_CREDENTIALS_CONTENT: ${{ secrets.CLOUD_CREDENTIALS_CONTENT }}
          GPG_PASSPHRASE: ''
      - name: Compute PocketIC server path
        id: pocket-ic-server-path
        run: echo "POCKET_IC_BIN=$(pwd)/$(bazel cquery //rs/pocket_ic_server:pocket-ic-server --output=files)" >> $GITHUB_ENV
      - name: Tests
        run: |
          export RUST_LOG=debug
          echo $POCKET_IC_BIN
          ls -l $POCKET_IC_BIN
          cargo test --locked -p pocket-ic hyper_issue
