name: PocketIC macOS Intel
on:
  pull_request:
    paths:
      - packages/pocket-ic/**
      - rs/pocket_ic_server/**
  schedule:
    - cron: "0 1 * * *"

# runs for the same workflow are cancelled on PRs but not on master
# explanation: on push to master head_ref is not set, so we want it to fall back to run_id so it is not cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bazel-build-pocket-ic:
    name: Bazel Build macOS Intel
    timeout-minutes: 130
    runs-on:
      labels: macOS
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 256 || 0 }}
      - name: Set PATH
        run: |
          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "$HOME/.cargo/bin:" >> $GITHUB_PATH
          # use llvm-clang instead of apple's
          echo "CC=/usr/local/opt/llvm/bin/clang" >> "$GITHUB_ENV"
      - name: Build PocketIC server
        run: |
          bazel build //rs/pocket_ic_server:pocket-ic-server
      - name: Compute PocketIC server path
        id: pocket-ic-server-path
        run: echo "pocket_ic_server_path=$(bazel cquery //rs/pocket_ic_server:pocket-ic-server --output=files)" >> $GITHUB_OUTPUT
      - name: Upload PocketIC server
        uses: actions/upload-artifact@v4
        with:
          name: pocket-ic-server
          path: ${{ steps.pocket-ic-server-path.outputs.pocket_ic_server_path }}
      - name: Build PocketIC test canister
        run: |
          bazel build //packages/pocket-ic/test_canister:test_canister
      - name: Compute PocketIC test canister path
        id: pocket-ic-test-canister-path
        run: echo "pocket_ic_test_canister_path=$(bazel cquery //packages/pocket-ic/test_canister:test_canister --output=files)" >> $GITHUB_OUTPUT
      - name: Upload PocketIC test canister
        uses: actions/upload-artifact@v4
        with:
          name: pocket-ic-test-canister
          path: ${{ steps.pocket-ic-test-canister-path.outputs.pocket_ic_test_canister_path }}

  pocket-ic-lint-on-macos-intel:
    name: PocketIC Lint on macOS Intel
    runs-on:
      labels: macOS
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 256 || 0 }}
      - name: Linting
        run: |
          cargo clippy -p pocket-ic --locked --all-features --all-targets -- -D warnings -D clippy::all -D clippy::mem_forget -C debug-assertions=off
          
  pocket-ic-tests-on-macos-intel:
    name: PocketIC Tests on macOS Intel
    needs: [bazel-build-pocket-ic]
    runs-on:
      labels: macOS
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 256 || 0 }}
      - name: Download PocketIC server
        uses: actions/download-artifact@v4
        with:
          name: pocket-ic-server
      - name: Download PocketIC test canister
        uses: actions/download-artifact@v4
        with:
          name: pocket-ic-test-canister
      - name: Tests
        run: |
          cargo test --locked -p pocket-ic
