# This is just a temporarily location for testing; when merged, this should be renamed
# and perhapsed merged into some other file

name: Fixture generation and upload
on:
  pull_request: 

jobs:
  upload-fixtures:
    name: Upload fixtures
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dfinity/ic-build@sha256:26cc347efa50935342742acddfb5d710fae1982d401911013ad8750f0603c590
    env:
      AWS_SHARED_CREDENTIALS_CONTENT: ${{ secrets.AWS_SHARED_CREDENTIALS_FILE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate and upload fixtures
        uses: ./.github/actions/bazel-test-all/
        with:
          BAZEL_COMMAND: "build"
          BAZEL_TARGETS: "//publish/fixtures:upload_fixtures"
          BAZEL_CI_CONFIG: "--config=ci --repository_cache=/cache/bazel"
          # check if PR title contains release and set timeout filters accordingly
          RUN_ON_DIFF_ONLY: 'false'
          HONEYCOMB_API_TOKEN: ${{ secrets.HONEYCOMB_API_TOKEN }}
      - name: Commit the new fixtures
        shell: bash
        run: |
          set -x
          cp bazel-bin/release_fixtures.bzl release_fixtures.bzl
          git add release_fixtures.bzl
          git commit -m "Release CI: Update release fixtures"
      - name: Open a PR with the new fixtures
        # TODO: check that this is allowed by the repo settings;
        # see https://github.com/marketplace/actions/create-pull-request#workflow-permissions
        uses: peter-evans/create-pull-request@v6
        with:
          # Do we need to do auth here?
          # token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update release fixtures
          title: Update release fixtures
          body: |
            This PR updates the release fixtures.
          branch: update-release-fixtures
          base: master
