# This is just a temporarily location for testing; when merged, this should be renamed
# and perhapsed merged into some other file

name: Fixture generation and upload
on:
  pull_request: 

jobs:
  upload-fixtures:
    name: Upload fixtures
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dfinity/ic-build@sha256:26cc347efa50935342742acddfb5d710fae1982d401911013ad8750f0603c590
    env:
      AWS_SHARED_CREDENTIALS_CONTENT: ${{ secrets.AWS_SHARED_CREDENTIALS_FILE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate and upload fixtures
        shell: bash
        run: |
          AWS_CREDS="${HOME}/.aws/credentials"
          mkdir -p "$(dirname "${AWS_CREDS}")"

          # handle github and gitlab differently
          if [ -n "${AWS_SHARED_CREDENTIALS_FILE+x}" ]; then
              ln -fs "${AWS_SHARED_CREDENTIALS_FILE}" "${AWS_CREDS}"
          elif [ -n "${AWS_SHARED_CREDENTIALS_CONTENT+x}" ]; then
              echo "$AWS_SHARED_CREDENTIALS_CONTENT" >"$AWS_CREDS"
          else
              echo '$AWS_SHARED_CREDENTIALS_CONTENT or $AWS_SHARED_CREDENTIALS_FILE has to be set' >&2
              exit 1
          fi
          
          bazel build //publish/fixtures:upload_fixtures
      - name: Commit the new fixtures
        shell: bash
        run: |
          set -x
          cp bazel-bin/release_fixtures.bzl release_fixtures.bzl
          git add release_fixtures.bzl
          git commit -m "Release CI: Update release fixtures"
      - name: Open a PR with the new fixtures
        # TODO: check that this is allowed by the repo settings;
        # see https://github.com/marketplace/actions/create-pull-request#workflow-permissions
        uses: peter-evans/create-pull-request@v6
        with:
          # Do we need to do auth here?
          # token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update release fixtures
          title: Update release fixtures
          body: |
            This PR updates the release fixtures.
          branch: update-release-fixtures
          base: master
