name: Release `canscan`

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v1.0.0)"
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Build canscan with Bazel
        run: |
          bazel build //canscan:canscan
          mkdir -p dist
          cp bazel-bin/canscan/canscan dist/canscan

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: "Canscan ${{ github.event.inputs.version }}"
          files: dist/canscan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
