name: Rosetta Release

on:
  push:

permissions:
  contents: write

env:
  ROSETTA_RELEASE_VERSION: ${{ github.event.inputs.rosetta_release_version }}
  ICRC_ROSETTA_RELEASE_VERSION: ${{ github.event.inputs.icrc_rosetta_release_version }}

jobs:
  rosetta-release:
    runs-on:
      labels: dind-large
    container:
      image: ghcr.io/dfinity/ic-build@sha256:9b554adf2402a705f962ad65cc9ec37596d2bd8a7ff5d3ee97b5a933c6dbef11
      options: >-
        -e NODE_NAME --privileged --cgroupns host
    environment: DockerHub
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker
        run: |
          podman login \
            --compat-auth-file="$HOME/.docker/config.json" \
            -u ${{ vars.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }} docker.io

