[package]
name = "ic-nervous-system-runtime"
version = "0.0.1"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
ic-base-types = { path = "../../types/base_types" }
ic-stable-structures = { workspace = true }
maplit = { workspace = true }
num-traits = { workspace = true }
