[package]
name = "ic-crypto-test-utils-metrics"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-crypto-internal-logmon = { path = "../../internal/logmon" }
ic-metrics = { path = "../../../monitoring/metrics" }
ic-test-utilities-metrics = { path = "../../../test_utilities/metrics" }
prometheus = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
